#pragma once
#include <stdint.h>

#define SYS_INTERFACE_OWNER_MAP(X) \
  X(OWNER_SYS_INTERFACE_BASE, 0xA600, "OWNER_SYS_INTERFACE_BASE") \
  X(OWNER_SYS_INTERFACE_DECODE, 0xA601, "OWNER_SYS_INTERFACE_DECODE")

#define SYS_ERROR_INTERFACE_MAP(X)
