#pragma once

#define SYS_INTERFACE_OWNER_MAP(X)                                \
  X(OWNER_SYS_INTERFACE_BASE, 0xA600, "OWNER_SYS_INTERFACE_BASE") \
  X(OWNER_SYS_INTERFACE_DECODE, 0xA601, "OWNER_SYS_INTERFACE_DECODE")

#define SYS_INTERFACE_ERROR_MAP(X) X(ERR_SYS_INTERFACE_BASE, 0xA600, "ERR_SYS_INTERFACE_BASE")
