#pragma once

#define SYS_DEVICE_OWNER_MAP(X)                                           \
  X(OWNER_SYS_DEVICE_BASE, 0xA100, "DEVICE_BASE")                         \
  X(OWNER_SYS_DEVICE_INSTALL, 0xA101, "OWNER_SYS_DEVICE_INSTALL")         \
  X(OWNER_SYS_DEVICE_UNINSTALL, 0xA102, "OWNER_SYS_DEVICE_UNINSTALL")     \
  X(OWNER_SYS_DEVICE_RESET, 0xA103, "OWNER_SYS_DEVICE_RESET")             \
  X(OWNER_SYS_DEVICE_GET_BY_ID, 0xA104, "OWNER_SYS_DEVICE_GET_BY_ID")     \
  X(OWNER_SYS_DEVICE_SUSPEND, 0xA105, "OWNER_SYS_DEVICE_SUSPEND")         \
  X(OWNER_SYS_DEVICE_RESUME, 0xA106, "OWNER_SYS_DEVICE_RESUME")           \
  X(OWNER_SYS_DEVICE_SUSPEND_ALL, 0xA107, "OWNER_SYS_DEVICE_SUSPEND_ALL") \
  X(OWNER_SYS_DEVICE_RESUME_ALL, 0xA108, "OWNER_SYS_DEVICE_RESUME_ALL")   \
  X(OWNER_SYS_DEVICE_FREEZE, 0xA109, "OWNER_SYS_DEVICE_FREEZE")           \
  X(OWNER_SYS_DEVICE_SYNC, 0xA10A, "OWNER_SYS_DEVICE_SYNC")               \
  X(OWNER_SYS_DEVICE_FREEZE_ALL, 0xA10B, "OWNER_SYS_DEVICE_FREEZE_ALL")   \
  X(OWNER_SYS_DEVICE_SYNC_ALL, 0xA10C, "OWNER_SYS_DEVICE_SYNC_ALL")

#define SYS_DEVICE_ERROR_MAP(X)                         \
  X(ERR_SYS_DEVICE_BASE, 0xA100, "ERR_SYS_DEVICE_BASE") \
  X(ERR_ALREADY_EXISTS, 0xA101, "ERR_ALREADY_EXISTS")   \
  X(ERR_DEVICE_INSTALL_FAILED, 0xA102, "ERR_DEVICE_INSTALL_FAILED")

#define SYS_I2C_OWNER_MAP(X)                                                                \
  X(OWNER_SYS_I2C_BASE, 0xA200, "OWNER_SYS_I2C_BASE")                                       \
  X(OWNER_SYS_I2C_MASTER_TRANSMIT, 0xA201, "OWNER_SYS_I2C_MASTER_TRANSMIT")                 \
  X(OWNER_SYS_I2C_MASTER_TRANSMIT_RECEIVE, 0xA202, "OWNER_SYS_I2C_MASTER_TRANSMIT_RECEIVE") \
  X(OWNER_SYS_I2C_ADD_DRIVER, 0xA203, "OWNER_SYS_I2C_ADD_DRIVER")                           \
  X(OWNER_SYS_I2C_REMOVE_DRIVER, 0xA204, "OWNER_SYS_I2C_REMOVE_DRIVER")                     \
  X(OWNER_SYS_I2C_INIT, 0XA206, "OWNER_SYS_I2C_INIT")                                       \
  X(OWNER_SYS_I2C_DEVICE_PRESENT, 0XA207, "OWNER_SYS_I2C_DEVICE_PRESENT")

#define SYS_I2C_ERROR_MAP(X)                                              \
  X(ERR_SYS_I2C_BASE, 0xA200, "ERR_SYS_I2C_BASE")                         \
  X(ERR_I2C_TRANSMISSION_FAILURE, 0xA201, "ERR_I2C_TRANSMISSION_FAILURE") \
  X(ERR_I2C_DEV_NOT_FOUND, 0xA202, "ERR_I2C_DEV_NOT_FOUND")               \
  X(ERR_I2C_TIMEOUT, 0xA203, "ERR_I2C_TIMEOUT")

#define SYS_IO_OWNER_MAP(X)                                                   \
  X(OWNER_SYS_IO_BASE, 0xA300, "OWNER_SYS_IO_BASE")                           \
  X(OWNER_SYS_IO_RESET, 0xA301, "OWNER_SYS_IO_RESET")                         \
  X(OWNER_SYS_IO_DRIVER_RESET, 0xA302, "OWNER_SYS_IO_DRIVER_RESET")           \
  X(OWNER_SYS_IO_SET_MODE, 0xA303, "OWNER_SYS_IO_SET_MODE")                   \
  X(OWNER_SYS_IO_CONFIGURE_INTR, 0xA304, "OWNER_SYS_IO_CONFIGURE_INTR")       \
  X(OWNER_SYS_IO_SET_LEVEL, 0xA305, "OWNER_SYS_IO_SET_LEVEL")                 \
  X(OWNER_SYS_IO_GET_LEVEL, 0xA306, "OWNER_SYS_IO_GET_LEVEL")                 \
  X(OWNER_SYS_IO_TOGGLE, 0xA307, "OWNER_SYS_IO_TOGGLE")                       \
  X(OWNER_SYS_IO_GET_VOLTAGE, 0xA308, "OWNER_SYS_IO_GET_VOLTAGE")             \
  X(OWNER_SYS_IO_SET_VOLTAGE, 0xA309, "OWNER_SYS_IO_SET_VOLTAGE")             \
  X(OWNER_SYS_IO_REGISTER_DRIVER, 0xA30A, "OWNER_SYS_IO_REGISTER_DRIVER")     \
  X(OWNER_SYS_IO_DESTROY, 0xA30B, "OWNER_SYS_IO_DESTROY")                     \
  X(OWNER_SYS_IO_SET_PWM_FREQUENCY, 0xA30C, "OWNER_SYS_IO_SET_PWM_FREQUENCY") \
  X(OWNER_SYS_IO_SET_PWM_DUTY, 0xA30D, "OWNER_SYS_IO_SET_PWM_DUTY")           \
  X(OWNER_SYS_IO_UNREGISTER_DRIVER, 0xA30E, "OWNER_SYS_IO_UNREGISTER_DRIVER")

#define SYS_IO_ERROR_MAP(X)                                                   \
  X(ERR_SYS_IO_BASE, 0xA300, "ERR_SYS_IO_BASE")                               \
  X(ERR_SYS_IO_FEATURE_UNAVAILABLE, 0xA301, "ERR_SYS_IO_FEATURE_UNAVAILABLE") \
  X(ERR_SYS_IO_PIN_IN_OTHER_USE, 0xA302, "ERR_SYS_IO_PIN_IN_OTHER_USE")       \
  X(ERR_SYS_IO_PIN_DOES_NOT_EXIST, 0xA303, "ERR_SYS_IO_PIN_DOES_NOT_EXIST")   \
  X(ERR_SYS_IO_MODE_UNAVAILABLE, 0xA304, "ERR_SYS_IO_MODE_UNAVAILABLE")

#define SYS_POWER_OWNER_MAP(X)                                                            \
  X(OWNER_SYS_POWER_BASE, 0xA400, "OWNER_SYS_POWER_BASE")                                 \
  X(OWNER_SYS_POWER_BUDGET_UPDATE_SOURCE, 0xA401, "OWNER_SYS_POWER_BUDGET_UPDATE_SOURCE") \
  X(OWNER_SYS_POWER_REGISTER_VREG, 0xA402, "OWNER_SYS_POWER_REGISTER_VREG`")              \
  X(OWNER_SYS_POWER_REGISTER_MONITOR, 0xA403, "OWNER_SYS_POWER_REGISTER_MONITOR")         \
  X(OWNER_SYS_POWER_REGISTER_USB_PD, 0xA404, "OWNER_SYS_POWER_REGISTER_USB_PD")           \
  X(OWNER_SYS_POWER_UNREGISTER, 0xA405, "OWNER_SYS_POWER_UNREGISTER")                     \
  X(OWNER_SYS_VREG_SET_ENABLE, 0xA406, "OWNER_SYS_VREG_SET_ENABLE")                       \
  X(OWNER_SYS_VREG_SET_VOLTAGE, 0xA407, "OWNER_SYS_VREG_SET_VOLTAGE")                     \
  X(OWNER_SYS_VREG_SET_CURRENT, 0xA408, "OWNER_SYS_VREG_SET_CURRENT")                     \
  X(OWNER_SYS_VREG_ADD_CALLBACK, 0xA409, "OWNER_SYS_VREG_ADD_CALLBACK")                   \
  X(OWNER_SYS_POWER_MONITOR_GET_VOLTAGE, 0xA40A, "OWNER_SYS_POWER_MONITOR_GET_VOLTAGE")   \
  X(OWNER_SYS_POWER_MONITOR_GET_CURRENT, 0xA40B, "OWNER_SYS_POWER_MONITOR_GET_CURRENT")   \
  X(OWNER_SYS_POWER_MONITOR_ADD_CALLBACK, 0xA40C, "OWNER_SYS_POWER_MONITOR_ADD_CALLBACK") \
  X(OWNER_SYS_POWER_USB_PD_SET, 0xA40D, "OWNER_SYS_POWER_USB_PD_SET")                     \
  X(OWNER_SYS_POWER_USB_PD_LIST, 0xA40E, "OWNER_SYS_POWER_USB_PD_LIST")                   \
  X(OWNER_SYS_POWER_USB_PD_GET_LIMITS, 0xA40F, "OWNER_SYS_POWER_USB_PD_GET_LIMITS")

#define SYS_POWER_ERROR_MAP(X)                        \
  X(ERR_SYS_POWER_BASE, 0xA400, "ERR_SYS_POWER_BASE") \
  X(ERR_POWER_BUDGET_EXCEEDED, 0xA401, "ERR_POWER_BUDGET_EXCEEDED")

#define SYS_BLE_OWNER_MAP(X)                                                   \
  X(OWNER_SYS_BLE_BASE, 0xA500, "OWNER_SYS_BLE_BASE")                         \
  X(OWNER_SYS_BLE_CREATE, 0xA501, "OWNER_SYS_BLE_CREATE")                     \
  X(OWNER_SYS_BLE_SERVICE_CREATE, 0xA502, "OWNER_SYS_BLE_SERVICE_CREATE")     \
  X(OWNER_SYS_BLE_SERVICE_REMOVE, 0xA503, "OWNER_SYS_BLE_SERVICE_REMOVE")     \
  X(OWNER_SYS_BLE_CHAR_CREATE, 0xA504, "OWNER_SYS_BLE_CHAR_CREATE")           \
  X(OWNER_SYS_BLE_CHAR_REMOVE, 0xA505, "OWNER_SYS_BLE_CHAR_REMOVE")           \
  X(OWNER_SYS_BLE_CHAR_ASSIGN_TX, 0xA506, "OWNER_SYS_BLE_CHAR_ASSIGN_TX")     \
  X(OWNER_SYS_BLE_CALLBACK_REGISTER, 0xA507, "OWNER_SYS_BLE_CALLBACK_REGISTER") \
  X(OWNER_SYS_BLE_SEND, 0xA508, "OWNER_SYS_BLE_SEND")                         \
  X(OWNER_SYS_BLE_DATABASE_SYNC, 0xA509, "OWNER_SYS_BLE_DATABASE_SYNC")       \
  X(OWNER_SYS_BLE_GET_STATUS, 0xA50A, "OWNER_SYS_BLE_GET_STATUS")

#define SYS_BLE_ERROR_MAP(X)                             \
  X(ERR_SYS_BLE_BASE, 0xA500, "ERR_SYS_BLE_BASE")

#define SYS_INTERFACE_OWNER_MAP(X)                                             \
  X(OWNER_SYS_INTERFACE_BASE, 0xA600, "OWNER_SYS_INTERFACE_BASE")             \
  X(OWNER_SYS_INTERFACE_DECODE, 0xA601, "OWNER_SYS_INTERFACE_DECODE")

#define SYS_INTERFACE_ERROR_MAP(X)                                             \
  X(ERR_SYS_INTERFACE_BASE, 0xA600, "ERR_SYS_INTERFACE_BASE")

