// Generated by data-structures/auto-annotations/vm/generate-vm-blocks.py from the //#vm-block directives of the block headers - do not edit.
#pragma once

/* Included by blocks/vm_blocks_table.c only: every block header, and the palette entries by id. An entry is the
   block's body and check (by name: vm_blk_<name>, vm_verify_<name>), the pin shape its //@in / //@out / //@enables
   directives declare (vm_block_verify() enforces it at load) and the size of its state struct. */

#include "vm_block_action.h"
#include "vm_block_clone.h"
#include "vm_block_edge.h"
#include "vm_block_expr.h"
#include "vm_block_expr_bit.h"
#include "vm_block_for.h"
#include "vm_block_if.h"
#include "vm_block_io_set_level.h"
#include "vm_block_io_toggle.h"
#include "vm_block_latch.h"
#include "vm_block_on_event.h"
#include "vm_block_periodic.h"
#include "vm_block_set.h"
#include "vm_block_switch.h"
#include "vm_block_timer.h"

#define VM_BLOCK_TABLE_ENTRIES \
  [VM_BLK_EXPR] = {.run = vm_blk_expr, .check = vm_verify_expr, .min_in = 0, .max_in = CONFIG_VM_BLOCK_MAX_IN, .min_q = 1, .max_q = 1, .min_en = 0, .required_in = 0x0u, .state_len = sizeof(vm_expr_code_t)}, \
  [VM_BLK_EXPR_BIT] = {.run = vm_blk_expr_bit, .check = vm_verify_expr_bit, .min_in = 0, .max_in = CONFIG_VM_BLOCK_MAX_IN, .min_q = 1, .max_q = 1, .min_en = 0, .required_in = 0x0u, .state_len = sizeof(vm_expr_code_t)}, \
  [VM_BLK_IF] = {.run = vm_blk_if, .min_in = 1, .max_in = 1, .min_q = 2, .max_q = 2, .min_en = 0, .required_in = 0x1u, .state_len = 0}, \
  [VM_BLK_SWITCH] = {.run = vm_blk_switch, .min_in = 1, .max_in = 1, .min_q = 1, .max_q = CONFIG_VM_BLOCK_MAX_OUT, .min_en = 0, .required_in = 0x1u, .state_len = 0}, \
  [VM_BLK_FOR] = {.run = vm_blk_for, .check = vm_verify_for, .min_in = 0, .max_in = 3, .min_q = 0, .max_q = 1, .min_en = 0, .required_in = 0x0u, .state_len = sizeof(vm_for_code_t)}, \
  [VM_BLK_SET] = {.run = vm_blk_set, .min_in = 2, .max_in = 2, .min_q = 0, .max_q = 0, .min_en = 0, .required_in = 0x3u, .state_len = 0}, \
  [VM_BLK_CLONE] = {.run = vm_blk_clone, .min_in = 2, .max_in = 2, .min_q = 0, .max_q = 0, .min_en = 0, .required_in = 0x3u, .state_len = 0}, \
  [VM_BLK_EDGE] = {.run = vm_blk_edge, .check = vm_verify_edge, .min_in = 0, .max_in = 0, .min_q = 0, .max_q = 0, .min_en = 1, .required_in = 0x0u, .state_len = sizeof(vm_block_edge_data_t)}, \
  [VM_BLK_TIMER] = {.run = vm_blk_timer, .check = vm_verify_timer, .min_in = 1, .max_in = 2, .min_q = 0, .max_q = 1, .min_en = 0, .required_in = 0x1u, .state_len = sizeof(vm_block_timer_data_t)}, \
  [VM_BLK_IO_SET_LEVEL] = {.run = vm_blk_io_set_level, .check = vm_verify_io_set_level, .min_in = 0, .max_in = 2, .min_q = 0, .max_q = 0, .min_en = 0, .required_in = 0x0u, .state_len = sizeof(vm_block_io_set_level_data_t)}, \
  [VM_BLK_IO_TOGGLE] = {.run = vm_blk_io_toggle, .check = vm_verify_io_toggle, .min_in = 0, .max_in = 1, .min_q = 0, .max_q = 0, .min_en = 0, .required_in = 0x0u, .state_len = sizeof(vm_block_io_toggle_data_t)}, \
  [VM_BLK_LATCH] = {.run = vm_blk_latch, .check = vm_verify_latch, .min_in = 0, .max_in = 1, .min_q = 0, .max_q = 0, .min_en = 1, .required_in = 0x0u, .state_len = sizeof(vm_block_latch_data_t)}, \
  [VM_BLK_PERIODIC] = {.run = vm_blk_periodic, .check = vm_verify_periodic, .min_in = 0, .max_in = 1, .min_q = 0, .max_q = 0, .min_en = 0, .required_in = 0x0u, .state_len = sizeof(vm_block_periodic_data_t)}, \
  [VM_BLK_ACTION] = {.run = vm_blk_action, .check = vm_verify_action, .min_in = 0, .max_in = 1, .min_q = 0, .max_q = 0, .min_en = 0, .required_in = 0x0u, .state_len = sizeof(vm_block_action_data_t)}, \
  [VM_BLK_ON_EVENT] = {.run = vm_blk_on_event, .min_in = 0, .max_in = 0, .min_q = 0, .max_q = 2, .min_en = 0, .required_in = 0x0u, .state_len = sizeof(vm_block_on_event_data_t)},
