// Generated by data-structures/auto-annotations/vm/generate-vm-blocks.py from the //#vm-block directives of the block headers - do not edit.
#pragma once

/* The palette ids: the @id of every //#vm-block. The id is the index into g_vm_block_types[] (blocks/vm_blocks_table.c)
   and the block_type byte on the wire, so a number is never reused for another block. */

#define VM_BLK_NONE 0  // reserved: an unset block_type is not runnable
#define VM_BLK_EXPR 1  // Expression -- vm_block_expr.h
#define VM_BLK_EXPR_BIT 2  // Bit Expression -- vm_block_expr_bit.h
#define VM_BLK_IF 3  // If -- vm_block_if.h
#define VM_BLK_SWITCH 4  // Switch -- vm_block_switch.h
#define VM_BLK_FOR 5  // For -- vm_block_for.h
#define VM_BLK_SET 6  // Set -- vm_block_set.h
#define VM_BLK_CLONE 7  // Clone -- vm_block_clone.h
#define VM_BLK_EDGE 8  // Edge -- vm_block_edge.h
#define VM_BLK_TIMER 9  // Timer -- vm_block_timer.h
#define VM_BLK_IO_SET_LEVEL 10  // Set Pin Level -- vm_block_io_set_level.h
#define VM_BLK_IO_TOGGLE 11  // Toggle Pin -- vm_block_io_toggle.h
#define VM_BLK_LATCH 12  // Latch -- vm_block_latch.h
#define VM_BLK_PERIODIC 13  // Every -- vm_block_periodic.h
#define VM_BLK_ACTION 14  // Run Action -- vm_block_action.h
#define VM_BLK_ON_EVENT 15  // On Event -- vm_block_on_event.h
