#pragma once

// Shifted owner ids into A100 range to avoid colliding with RIK error codes (A000..A0FF)
#define RIK_OWNER_MAP(X) \
    X(OWNER_RIK_INTERRUPTS_CONFIG,     0xA100, "OWNER_RIK_INTERRUPTS_CONFIG") \
    X(OWNER_RIK_DRIVER_INIT_GPIO_EXPANDER,  0xA101, "OWNER_RIK_DRIVER_INIT_GPIO_EXPANDER") \
    X(OWNER_RIK_DRIVER_INIT_CURRENT_MONITOR,   0xA102, "OWNER_RIK_DRIVER_INIT_CURRENT_MONITOR") \
    X(OWNER_RIK_DRIVER_INIT_VREG,  0xA103, "OWNER_RIK_DRIVER_INIT_VREG") \
    X(OWNER_RIK_DRIVER_INIT_BLE,       0xA104, "OWNER_RIK_DRIVER_INIT_BLE") \
    X(OWNER_RIK_DRIVER_INIT_INTERFACE, 0xA105, "OWNER_RIK_DRIVER_INIT_INTERFACE") \
    X(OWNER_RIK_DRIVER_INIT_I2C,       0xA106, "OWNER_RIK_DRIVER_INIT_I2C") \
    X(OWNER_RIK_TX_SEND,               0xA107, "OWNER_RIK_TX_SEND") \
    X(OWNER_RIK_RX_RECEIVE,            0xA108, "OWNER_RIK_RX_RECEIVE") \
    X(OWNER_RIK_DRIVER_INIT,           0xA109, "OWNER_RIK_DRIVER_INIT") \
    X(OWNER_RIK_DRIVER_INIT_ADC_EXPANDER, 0xA10A, "OWNER_RIK_DRIVER_INIT_ADC_EXPANDER") \
    X(OWNER_RIK_DRIVER_INIT_PWM_EXPANDER, 0xA10B, "OWNER_RIK_DRIVER_INIT_PWM_EXPANDER") \
    X(OWNER_RIK_DRIVER_INIT_POWER_MANAGER, 0xA10C, "OWNER_RIK_DRIVER_INIT_POWER_MANAGER") \
    X(OWNER_RIK_DRIVER_INIT_IO_MANAGER, 0xA10D, "OWNER_RIK_DRIVER_INIT_IO_MANAGER") 


#define RIK_ERROR_MAP(X) \
    X(ERR_RIK_BASE,              0xA000, "ERR_RIK_BASE") \
    X(ERR_TX_BUFFER_FULL,        0xA001, "ERR_TX_BUFFER_FULL") \
    X(ERR_INTERFACE_UNAVAILABLE, 0xA002, "ERR_INTERFACE_UNAVAILABLE") \
    X(ERR_TIMEOUT,               0xA003, "ERR_TIMEOUT") \
    X(ERR_SIZE_TOO_LARGE,        0xA004, "ERR_SIZE_TOO_LARGE")

