#pragma once

#define RIK_OWNER_MAP(X) \
    X(OWNER_RIK_INTERRUPTS_CONFIG,     0xA001, "OWNER_RIK_INTERRUPTS_CONFIG") \
    X(OWNER_RIK_DRIVER_INIT_TCA6424A,  0xA002, "OWNER_RIK_DRIVER_INIT_TCA6424A") \
    X(OWNER_RIK_DRIVER_INIT_INA3221,   0xA003, "OWNER_RIK_DRIVER_INIT_INA3221") \
    X(OWNER_RIK_DRIVER_INIT_TPS55289,  0xA004, "OWNER_RIK_DRIVER_INIT_TPS55289") \
    X(OWNER_RIK_DRIVER_INIT_BLE,       0xA005, "OWNER_RIK_DRIVER_INIT_BLE") \
    X(OWNER_RIK_DRIVER_INIT_INTERFACE, 0xA006, "OWNER_RIK_DRIVER_INIT_INTERFACE") \
    X(OWNER_RIK_DRIVER_INIT_I2C,       0xA007, "OWNER_RIK_DRIVER_INIT_I2C") \
    X(OWNER_RIK_TX_SEND,               0xA008, "OWNER_RIK_TX_SEND") \
    X(OWNER_RIK_RX_RECEIVE,            0xA009, "OWNER_RIK_RX_RECEIVE")

#define RIK_ERROR_MAP(X) \
    X(ERR_RIK_BASE,              0xA000, "ERR_RIK_BASE") \
    X(ERR_TX_BUFFER_FULL,        0xA001, "ERR_TX_BUFFER_FULL") \
    X(ERR_INTERFACE_UNAVAILABLE, 0xA002, "ERR_INTERFACE_UNAVAILABLE") \
    X(ERR_TIMEOUT,               0xA003, "ERR_TIMEOUT") \
    X(ERR_SIZE_TOO_LARGE,        0xA004, "ERR_SIZE_TOO_LARGE")
