// Generated by data-structures/auto-annotations/device/generate-devices.py from device_pca9685.json - do not edit.
#pragma once

#define PCA9685_MAX_PWM_VALUE 4095  // 12-bit duty
#define PCA9685_MIN_FREQUENCY_HZ 24  // prescaler 255 at the 25 MHz oscillator
#define PCA9685_MAX_FREQUENCY_HZ 1526  // prescaler 3
