#pragma once
#include <stdint.h>

#define SYS_BUFFERS_OWNER_MAP(X) \
  X(OWNER_SYS_BUFFERS_BASE, 0xA700, "OWNER_SYS_BUFFERS_BASE") \
  X(OWNER_SYS_BUFF_INIT, 0xA701, "OWNER_SYS_BUFF_INIT") \
  X(OWNER_SYS_BUFF_FREE, 0xA702, "OWNER_SYS_BUFF_FREE") \
  X(OWNER_SYS_BUFF_PUSH, 0xA703, "OWNER_SYS_BUFF_PUSH") \
  X(OWNER_SYS_BUFF_POP_FRAMED, 0xA704, "OWNER_SYS_BUFF_POP_FRAMED") \
  X(OWNER_SYS_BUFF_POP_RAW, 0xA705, "OWNER_SYS_BUFF_POP_RAW")

#define SYS_ERROR_BUFFERS_MAP(X)

/** @brief sys_buffers raises no tags of its own yet (see SYS_ERROR_BUFFERS_MAP above) - empty for the same reason. */
#define SYS_ERROR_BUFFERS_LOGGER_MAP(X)
