#pragma once

#define RIK_OWNER_MAP(X) \
    X(OWNER_RIK_INTERRUPTS_CONFIG,     0xa111, "OWNER_RIK_INTERRUPTS_CONFIG") \
    X(OWNER_RIK_DRIVER_INIT_TCA6424A,     0xa112, "OWNER_RIK_DRIVER_INIT_TCA6424A") \
    X(OWNER_RIK_DRIVER_INIT_INA3221,     0xa113, "OWNER_RIK_DRIVER_INIT_INA3221") \
    X(OWNER_RIK_DRIVER_INIT_TPS55289,     0xa114, "OWNER_RIK_DRIVER_INIT_TPS55289") \
    X(OWNER_RIK_DRIVER_INIT_BLE,     0xa115, "OWNER_RIK_DRIVER_INIT_BLE") \
    X(OWNER_RIK_DRIVER_INIT_INTERFACE,     0xa116, "OWNER_RIK_DRIVER_INIT_INTERFACE") \
    X(OWNER_RIK_DRIVER_INIT_I2C,     0xa117, "OWNER_RIK_DRIVER_INIT_I2C") \
    X(OWNER_RIK_TX_SEND,     0xa118, "OWNER_RIK_TX_SEND") \
    X(OWNER_RIK_RX_RECEIVE,     0xa119, "OWNER_RIK_RX_RECEIVE")

#define RIK_ERROR_MAP(X) \
    X(ERR_RIK_,        0x0111, "ERR_RIK_") \
    X(ERR_TX_BUFFER_FULL,        0x0112, "ERR_TX_BUFFER_FULL") \
    X(ERR_INTERFACE_UNAVAILABLE,        0x0113, "ERR_INTERFACE_UNAVAILABLE") \
    X(ERR_TIMEOUT,       0x0114, "ERR_TIMEOUT") \
    X(ERR_SIZE_TOO_LARGE, 0x0115, "ERR_SIZE_TOO_LARGE")
