#pragma once

#define STATUS_PAYLOAD_DEV_IO_ERR 2
#define STATUS_PAYLOAD_SYS_IO STATUS_PAYLOAD_DEV_IO_ERR

#define STA_PAYLOAD_MAKE_DEV_IO_ERR(dev_id, pin, extra) (((uint64_t)(dev_id) << 40) | ((uint64_t)(pin) << 32) | ((uint64_t)(extra) & 0xFFFFFFFF))
#define STA_PAYLOAD_GET_DEV_IO_ID(payload) ((uint8_t)((payload) >> 40))
#define STA_PAYLOAD_GET_DEV_IO_PIN(payload) ((uint8_t)(((payload) >> 32) & 0xFF))
#define STA_PAYLOAD_GET_DEV_IO_EXTRA(payload) ((uint32_t)((payload) & 0xFFFFFFFF))


#define SYS_IO_OWNER_MAP(X)                                                   \
  X(OWNER_SYS_IO_BASE, 0xA300, "OWNER_SYS_IO_BASE")                           \
  X(OWNER_SYS_IO_RESET, 0xA301, "OWNER_SYS_IO_RESET")                         \
  X(OWNER_SYS_IO_DRIVER_RESET, 0xA302, "OWNER_SYS_IO_DRIVER_RESET")           \
  X(OWNER_SYS_IO_SET_MODE, 0xA303, "OWNER_SYS_IO_SET_MODE")                   \
  X(OWNER_SYS_IO_CONFIGURE_INTR, 0xA304, "OWNER_SYS_IO_CONFIGURE_INTR")       \
  X(OWNER_SYS_IO_SET_LEVEL, 0xA305, "OWNER_SYS_IO_SET_LEVEL")                 \
  X(OWNER_SYS_IO_GET_LEVEL, 0xA306, "OWNER_SYS_IO_GET_LEVEL")                 \
  X(OWNER_SYS_IO_TOGGLE, 0xA307, "OWNER_SYS_IO_TOGGLE")                       \
  X(OWNER_SYS_IO_GET_VOLTAGE, 0xA308, "OWNER_SYS_IO_GET_VOLTAGE")             \
  X(OWNER_SYS_IO_SET_VOLTAGE, 0xA309, "OWNER_SYS_IO_SET_VOLTAGE")             \
  X(OWNER_SYS_IO_REGISTER_DRIVER, 0xA30A, "OWNER_SYS_IO_REGISTER_DRIVER")     \
  X(OWNER_SYS_IO_DESTROY, 0xA30B, "OWNER_SYS_IO_DESTROY")                     \
  X(OWNER_SYS_IO_SET_PWM_FREQUENCY, 0xA30C, "OWNER_SYS_IO_SET_PWM_FREQUENCY") \
  X(OWNER_SYS_IO_SET_PWM_DUTY, 0xA30D, "OWNER_SYS_IO_SET_PWM_DUTY")           \
  X(OWNER_SYS_IO_UNREGISTER_DRIVER, 0xA30E, "OWNER_SYS_IO_UNREGISTER_DRIVER")

#define SYS_IO_ERROR_MAP(X)                                                         \
  X(ERR_SYS_IO_BASE, 0xA300, "ERR_SYS_IO_BASE")                               \
  X(ERR_SYS_IO_FEATURE_UNAVAILABLE, 0xA301, "ERR_SYS_IO_FEATURE_UNAVAILABLE") \
  X(ERR_SYS_IO_PIN_IN_OTHER_USE, 0xA302, "ERR_SYS_IO_PIN_IN_OTHER_USE")       \
  X(ERR_SYS_IO_PIN_DOES_NOT_EXIST, 0xA303, "ERR_SYS_IO_PIN_DOES_NOT_EXIST")   \
  X(ERR_SYS_IO_MODE_UNAVAILABLE, 0xA304, "ERR_SYS_IO_MODE_UNAVAILABLE")
