#include "rik_devices_link.h"
#include "manager_io.h"
#include "manager_power.h"
#include "rik_shared.h"

void simple_callback(void* arg){
    ESP_LOGI("SIMPLE_CALLBACK", "Callback triggered with arg: %p", arg);
}


status_rep_t rik_link_pins(void){
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_PWM_EXPANDER_nOE, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_REGA_EN, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_REGB_EN, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));

    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV_OCPM, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV2_SLEEP, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV1_SLEEP, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV1_VMA_VSUP, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV1_VMB_REGB, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV2_VMA_REGA, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV2_VMB_VSUP, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));

    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_LED_1, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_LED_2, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));

    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV_1_EN1, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV_1_EN2, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV_1_EN3, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV_1_EN4, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));

    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV_1_IN1, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV_1_IN2, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV_1_IN3, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV_1_IN4, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_GPIO_EXPANDER_nRESET, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
 
    //********************INPUTS*************************** */
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_REGA_INT, SYS_GPIO_MODE_INPUT));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_REGB_INT, SYS_GPIO_MODE_INPUT));

    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_VUSB_OK, SYS_GPIO_MODE_INPUT));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_VEXT_OK, SYS_GPIO_MODE_INPUT));

    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_POWER_MONITOR_WARN, SYS_GPIO_MODE_INPUT));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_MONITOR_CRIT, SYS_GPIO_MODE_INPUT));

    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV2_FAULT, SYS_GPIO_MODE_INPUT));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV2_FAULT, SYS_GPIO_MODE_INPUT));

    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_PD_INT, SYS_GPIO_MODE_INPUT));
    
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_GPIO_EXPANDER_nINT, SYS_GPIO_MODE_INPUT_PULLUP));

    /*****************ADC INPUTS **********************************/
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV_1_IPROPI_1, SYS_GPIO_MODE_ADC));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV_1_IPROPI_2, SYS_GPIO_MODE_ADC));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV_1_IPROPI_3, SYS_GPIO_MODE_ADC));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV_1_IPROPI_4, SYS_GPIO_MODE_ADC));

    return STA_OK;
}

status_rep_t rik_link_callbacks(void){
    
}

