#include "rik_devices_link.h"
#include "manager_io.h"
#include "manager_power.h"
#include "rik_shared.h"
#include "manager_i2c.h"




status_rep_t rik_link_pins(void){
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_PWM_EXPANDER_nOE, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_REGA_EN, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_REGB_EN, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));

    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV_OCPM, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV2_SLEEP, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV1_SLEEP, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV1_VMA_VSUP, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV1_VMB_REGB, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV2_VMA_REGA, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV2_VMB_VSUP, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));

    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_LED_1, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_LED_2, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));

    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV_1_EN1, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV_1_EN2, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV_1_EN3, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV_1_EN4, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));

    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV_1_IN1, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV_1_IN2, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV_1_IN3, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV_1_IN4, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
    
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_GPIO_EXPANDER_nRESET, SYS_GPIO_MODE_OUTPUT_PUSH_PULL));
 
    //********************INPUTS*************************** */
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_REGA_INT, SYS_GPIO_MODE_INPUT));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_REGB_INT, SYS_GPIO_MODE_INPUT));

    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_VUSB_OK, SYS_GPIO_MODE_INPUT));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_VEXT_OK, SYS_GPIO_MODE_INPUT));

    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_POWER_MONITOR_WARN, SYS_GPIO_MODE_INPUT));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_MONITOR_CRIT, SYS_GPIO_MODE_INPUT));

    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV2_FAULT, SYS_GPIO_MODE_INPUT));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV2_FAULT, SYS_GPIO_MODE_INPUT));

    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_PD_INT, SYS_GPIO_MODE_INPUT));
    
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_GPIO_EXPANDER_nINT, SYS_GPIO_MODE_INPUT_PULLUP));
    
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_ADC_EXPANDER_ALERT, SYS_GPIO_MODE_INPUT_PULLUP));

    /*****************ADC INPUTS **********************************/
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV_1_IPROPI_1, SYS_GPIO_MODE_ADC));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV_1_IPROPI_2, SYS_GPIO_MODE_ADC));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV_1_IPROPI_3, SYS_GPIO_MODE_ADC));
    STA_RET_ON_ERR(SYS_GPIO_SET_MODE(RIK_IO_PIN_DRV_1_IPROPI_4, SYS_GPIO_MODE_ADC));

    return STA_OK;
}


extern void p_gpio_expander_intr_pin_callback(void* arg);
extern void p_current_monitor_intr_pin_warning_callback(void *arg);
extern void p_current_monitor_intr_pin_crit_callback(void *arg);
extern void p_vreg_intr_pin_fault_callback(void *arg);
extern void p_adc_expander_intr_pin_callback(void* arg);

status_rep_t rik_link_interrupts(void){

    STA_RET_ON_ERR(SYS_GPIO_REGISTER_CALLBACK(RIK_IO_PIN_GPIO_EXPANDER_nINT, SYS_GPIO_INTR_MODE_FALLING_EDGE, p_gpio_expander_intr_pin_callback, m_i2c_get_dev_handle(rik_gpio_expander_id)));
    STA_RET_ON_ERR(SYS_GPIO_REGISTER_CALLBACK(RIK_IO_PIN_POWER_MONITOR_WARN, SYS_GPIO_INTR_MODE_FALLING_EDGE, p_current_monitor_intr_pin_warning_callback, m_i2c_get_dev_handle(rik_current_monitor_id)));
    STA_RET_ON_ERR(SYS_GPIO_REGISTER_CALLBACK(RIK_IO_PIN_MONITOR_CRIT, SYS_GPIO_INTR_MODE_FALLING_EDGE, p_current_monitor_intr_pin_crit_callback, m_i2c_get_dev_handle(rik_current_monitor_id)));
    STA_RET_ON_ERR(SYS_GPIO_REGISTER_CALLBACK(RIK_IO_PIN_ADC_EXPANDER_ALERT, SYS_GPIO_INTR_MODE_FALLING_EDGE, p_adc_expander_intr_pin_callback, m_i2c_get_dev_handle(rik_adc_expander_id)));
    STA_RET_ON_ERR(SYS_GPIO_REGISTER_CALLBACK(RIK_IO_PIN_REGA_INT, SYS_GPIO_INTR_MODE_FALLING_EDGE, p_vreg_intr_pin_fault_callback, m_i2c_get_dev_handle(rik_vreg0_id)));
    STA_RET_ON_ERR(SYS_GPIO_REGISTER_CALLBACK(RIK_IO_PIN_REGB_INT, SYS_GPIO_INTR_MODE_FALLING_EDGE, p_vreg_intr_pin_fault_callback, m_i2c_get_dev_handle(rik_vreg1_id)));
    return STA_OK;
}