"""Generate the app's block descriptors, the palette index and the firmware's block registry from the block headers.

A block is a folder components/VM/blocks/<name>/ holding vm_block_<name>.h (and .c), <name>.display.json (what the editor shows,
written by hand) and <name>.md (the user guide). The header is the single source of truth for everything else: the generator
writes <name>.content.json next to it (what the block is: pins, payload layout, enums, rules). Adding a block needs no edit
here and no edit anywhere central. Nothing in this file names a block.

The header's `//@` lines stand next to what they describe; one block per header, all attached to its `//#vm-block` line:

  //#vm-block VM_BLK_<NAME> @id <1..255>        above the body prototype
  //@activation <enabled|triggered|enable-rising>
  //@enables required|optional                  at least one enable source (default optional)
  //@data <struct>                              above the private-state struct (custom_data)
  //@data-tail <text>                           variable bytes after it (bytecode blocks)
  //@opcodes <enum> @stack-max <C macro>        bytecode blocks: the opcode enum and the evaluator's stack depth
  //@rule <text> @error <ERR_TAG>               above vm_verify_<name>: what the load-time check rejects
  //@example <title> @in <values> [@consts <values>] @code <opcodes and operands> @result <value>

The pins are the members of the enums `vm_in_<name>_e` / `vm_out_<name>_e` (marked `//#block-enum`): `VM_IN_<NAME>_<PIN> = <index>,
//@in @value <kind> [@required] [@overrides <field>] ...`; a repeating pin is the last member `..._<PIN>_ANY` with `@repeat`. The
shape the firmware enforces at load comes from them: `@required` marks a pin the block cannot run without (min_in / min_q reach
the highest required pin, required_in is the bitmask of required inputs), the max counts are the numbered pins (or the Kconfig
limit with a repeating pin), and `//@enables required` asks for at least one enable source. Enums of one block are `//#block-enum`
(they go into its content.json); an enum several blocks use stays `//#ref-enum`. A type a state struct uses that the generator
cannot size is declared `//#vm-type <name> @size <n> @align <n>` (and asserted in C). The private-state struct is laid out here
(natural C alignment) and cross-checked against its _Static_assert(sizeof) and every _Static_assert(offsetof).

The generator also writes the firmware's registry: vm_block_ids.generated.h (the VM_BLK_<NAME> numbers) and
vm_blocks_registry.generated.h (every block header and the palette table entries: `vm_blk_<name>` / `vm_verify_<name>` by name,
that shape, and `sizeof` of the @data struct), used by blocks/vm_blocks_table.c. A `<name>.md` is copied to
app/docs/blocks/<name>.md (with its images/). Anything not understood is an error, so a typo never silently drops a fact.
Grammar: vm-annotations.md.

Usage:
  python data-structures/auto-annotations/vm/generate-vm-blocks.py [--check] [--skip-schema]
"""
import importlib.util
import json
import re
import struct
import sys
from pathlib import Path

try:
    import jsonschema
except ImportError:
    jsonschema = None

PROJECT_ROOT = Path(__file__).parents[3]
VM_ROOT = PROJECT_ROOT / "components" / "VM"
BLOCKS_DIR = VM_ROOT / "blocks"
OUT_DIR = PROJECT_ROOT / "data-structures" / "vm" / "blocks"
BLOCK_SCHEMA = PROJECT_ROOT / "data-structures" / "schema" / "vm-block.schema.json"
INDEX_SCHEMA = PROJECT_ROOT / "data-structures" / "schema" / "vm-blocks-index.schema.json"

HEAD_RE = re.compile(r"^VM_BLK_(\w+)\s+@id\s+(\d+)$")
IDS_HEADER = BLOCKS_DIR / "vm_block_ids.generated.h"
REGISTRY_HEADER = BLOCKS_DIR / "vm_blocks_registry.generated.h"
INCLUDE_RE = re.compile(r'^#include\s+"([\w.]+)"', re.MULTILINE)
GUIDE_DIR = PROJECT_ROOT / "app" / "docs" / "blocks"  # where the app reads block guides
GUIDE_MARK = "<!-- Generated by data-structures/auto-annotations/vm/generate-vm-blocks.py from"
GUIDE_IMAGE_RE = re.compile(r"(\]\()images/")
DISPLAY_FILES = {}  # header path -> (display.json, content.json), project-relative
DISPLAY_BLOCKS = {}  # block name -> the same, for the blocks the app reads from their folder
ENUM_MODULE = {}
C_INFO = {}  # block name -> what the firmware table entry needs (filled while the blocks are built)
C_GENERATED_MARK = "// Generated by data-structures/auto-annotations/vm/generate-vm-blocks.py from the //#vm-block directives of the block headers - do not edit."
START_RE = re.compile(r"^//#vm-block\b[ \t]*(?P<rest>.*)$")
DIRECTIVE_RE = re.compile(r"^//@(?P<keyword>[a-z][a-z0-9-]*)(?:[ \t]+(?P<rest>.*))?$")
TAG_RE = re.compile(r"(?:^|(?<=\s))@([a-z][a-z0-9-]*)(?=\s|$)")
PIN_RE = re.compile(r"^(?P<index>\*|\d+)\s+(?P<name>\w+)(?P<tags>(?:\s.*)?)$")
REF_RE = re.compile(r"\{(\w+)\}")
FIELD_RE = re.compile(r"^\s*(?P<type>[A-Za-z_][\w ]*?)\s+(?P<name>\w+)\s*(?:\[(?P<arr>\w*)\])?\s*;\s*(?://\s*(?P<comment>.*))?$")
OPTABLE_RE = r"//#vm-opcodes\s+{enum}\s*\n[^{{]*\{{(?P<body>.*?)\n\}};"
OPENTRY_RE = re.compile(r"\[(?P<sym>\w+)\]\s*=\s*\{\s*(?P<pops>\d+)\s*,\s*(?P<pushes>\d+)\s*,\s*VM_\w*?ARG_(?P<arg>NONE|INPUT|CONST)\s*\}")
ERROR_TAG_RE = re.compile(r"X\(\s*(ERR_\w+)\s*,\s*(0x[0-9A-Fa-f]+)\s*,")
IDENT_RE = re.compile(r"^[A-Za-z_]\w*$")

# What each `//@keyword` line of a block header takes: `one` once, `many` any number of times.
DIRECTIVES = {
    "activation": "one", "enables": "one", "data": "one", "data-tail": "one", "opcodes": "one",
    "rule": "many", "example": "many",
}
FACE_DIRECTIVES = {"title", "category", "block-description", "header", "eno", "always-detailed", "in", "out"}  # not in a header: see FACE_HINT
FACE_HINT = ("belong in the <name>.display.json (the face) or on the member of vm_in_<block>_e / vm_out_<block>_e (a pin: "
             "`VM_IN_<BLOCK>_<PIN> = 0, //@in @value <kind> ...`), not as a //@ line")
REQUIRED_DIRECTIVES = ("activation",)

# Tags per line kind. A tag outside its set, or given twice, is an error.
PIN_TAGS = {"repeat", "title", "description", "value", "overrides", "hidden-by-default", "id", "device-field", "required"}
FIELD_TAGS = {"description", "enum-ref", "runtime", "derived", "id", "device-field", "contract", "hidden-by-default", "let-user-select-available", "dynamic-input"}
ENO_TAGS = {"title", "description"}
RULE_TAGS = {"error"}
EXAMPLE_TAGS = {"in", "consts", "code", "result"}
FLAG_TAGS = {"hidden-by-default", "runtime", "required", "repeat"}

# (size, alignment) of the C types a state struct may use. Any other type is declared where it is defined, with
# `//#vm-type <name> @size <n> @align <n>` (and a _Static_assert of the same in C), so no block's type is named here.
TYPES = {
    "uint8_t": (1, 1), "int8_t": (1, 1), "bool": (1, 1), "char": (1, 1),
    "uint16_t": (2, 2), "int16_t": (2, 2),
    "uint32_t": (4, 4), "int32_t": (4, 4), "float": (4, 4),
    "uint64_t": (8, 8), "int64_t": (8, 8), "double": (8, 8),
}
VM_TYPE_RE = re.compile(r"^//#vm-type\s+(\w+)\s+@size\s+(\d+)\s+@align\s+(\d+)\s*$", re.MULTILINE)
DECLARED_TYPES = {}


def state_types():
    """TYPES plus every `//#vm-type` declared under components/VM."""
    if not DECLARED_TYPES:
        for header in sorted(VM_ROOT.rglob("*.h")):
            for name, size, align in VM_TYPE_RE.findall(header.read_text(encoding="utf-8", errors="ignore")):
                DECLARED_TYPES[name] = (int(size), int(align))
        DECLARED_TYPES["_scanned"] = (0, 0)
    return {**TYPES, **DECLARED_TYPES}


# What a pin reads or writes. Scalar kinds accept an object of any scalar type
# (B, U8, U32, I32, F, STR): the device converts on read and on write.
VALUE_KINDS = {
    "bool": "Read as true when non-zero / written 1 or 0. Any scalar object.",
    "u8": "Read or written as an unsigned 8-bit number. Any scalar object (converted).",
    "u32": "Read or written as an unsigned 32-bit number. Any scalar object (converted).",
    "i32": "Read or written as a signed 32-bit number. Any scalar object (converted).",
    "f32": "Read or written as a float. Any scalar object (converted).",
    "scalar": "Read in its own type; the block's behaviour depends on it (see the block). B, U8, U32, I32 or F.",
    "gate": "Written 1 while active and cleared quietly (0 without marking it updated) otherwise: wire it to enables.",
    "object": "A whole object or tree; source and destination must have the same types and counts.",
    "ptr-cell": "An element of a PTR object; the block hangs its own tree there.",
}
ACTIVATION_KINDS = {
    "enabled": "Runs every pass while its enables allow it (always, with no enables); resets or clears its outputs when disabled.",
    "triggered": "Runs when an input it watches is fresh (marked updated this pass) and it is enabled.",
    "enable-rising": "Runs once each time its enables turn it on.",
}
# What `@id <kind>` on a state field or a pin means (id_kind in the json).
ID_KINDS = {
    "device": "The id of a device created in the project. The field's `contract` says which devices fit (the ones that answer it).",
    "pin": "An index of an IO resource of the device in the field named by `device_field` (a pin, a channel: the editor's title says which).",
}
ARG_KINDS = {"NONE": "none", "INPUT": "input", "CONST": "const"}

# The C field types a pin of each value kind may take its constant from.
OVERRIDE_TYPES = {
    "bool": {"uint8_t", "bool"}, "u8": {"uint8_t"}, "u32": {"uint32_t", "uint16_t", "uint8_t"},
    "i32": {"int32_t", "int16_t", "int8_t"}, "f32": {"float"}, "scalar": set(TYPES),
}


def fail(message):
    raise SystemExit(f"ERROR: {message}")


# ---------------------------------------------------------------------------
# Lines and tags
# ---------------------------------------------------------------------------

def parse_tags(text, allowed, context):
    """(lead, tags): the text before the first tag, and `{tag: value}`. An unknown or repeated tag fails."""
    matches = list(TAG_RE.finditer(text))
    lead = (text[:matches[0].start()] if matches else text).strip()
    tags = {}
    for i, m in enumerate(matches):
        name = m.group(1)
        if name not in allowed:
            fail(f"{context}: unknown tag @{name} (this line takes: {', '.join('@' + t for t in sorted(allowed))})")
        if name in tags:
            fail(f"{context}: @{name} given twice")
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        value = text[m.end():end].strip()
        if name in FLAG_TAGS and value:
            fail(f"{context}: @{name} takes no value (got `{value}`)")
        tags[name] = value
    return lead, tags


def safe_int(expr, context):
    """An integer C constant expression (`0x1u`, `(1u << 0) | (1u << 2)`); nothing else."""
    text = re.sub(r"(?<=[0-9a-fA-F])[uUlL]+\b", "", expr.strip())
    if not text or not re.fullmatch(r"[0-9a-fA-FxX<>|&+()\s-]+", text):
        fail(f"{context}: cannot read `{expr.strip()}` as an integer constant")
    try:
        return int(eval(text, {"__builtins__": {}}, {}))  # noqa: S307 - the character set above admits only numbers and operators
    except Exception:
        fail(f"{context}: cannot read `{expr.strip()}` as an integer constant")


def split_top_level(text):
    """Split on commas outside brackets."""
    items, depth, start = [], 0, 0
    for i, ch in enumerate(text):
        if ch in "([{":
            depth += 1
        elif ch in ")]}":
            depth -= 1
        elif ch == "," and depth == 0:
            items.append(text[start:i])
            start = i + 1
    items.append(text[start:])
    return [item for item in items if item.strip()]


# ---------------------------------------------------------------------------
# Finding the blocks in a header
# ---------------------------------------------------------------------------

def scan_block(label, text):
    """The header's block: `{name, id, line, directives}` from its one `//#vm-block` line and every `//@` line of the file, or None
    when it has no `//#vm-block` (a shared header). The `//@` lines stand next to the element they describe."""
    lines = text.replace("\r\n", "\n").split("\n")
    heads = [(i, START_RE.match(line)) for i, line in enumerate(lines) if START_RE.match(line)]
    if len(heads) > 1:
        fail(f"{label}: {len(heads)} `//#vm-block` lines: one block per header (shared code goes in its own folder without one)")
    directives = []
    for k, line in enumerate(lines):
        if not line.lstrip().startswith("//@"):
            continue
        d = DIRECTIVE_RE.match(line.strip())
        if not d:
            fail(f"{label}:{k + 1}: malformed directive `{line.strip()}`")
        keyword = d.group("keyword")
        if keyword in FACE_DIRECTIVES:
            fail(f"{label}:{k + 1}: //@{keyword} {FACE_HINT}")
        if keyword not in DIRECTIVES:
            fail(f"{label}:{k + 1}: unknown directive //@{keyword} (known: {', '.join(sorted(DIRECTIVES))})")
        directives.append({"keyword": keyword, "rest": (d.group("rest") or "").strip(), "line": k + 1})
    if not heads:
        if directives:
            fail(f"{label}:{directives[0]['line']}: //@{directives[0]['keyword']} without a `//#vm-block VM_BLK_<NAME> @id <n>` line")
        return None
    i, m = heads[0]
    head = HEAD_RE.match(m.group("rest").strip())
    if not head:
        fail(f"{label}:{i + 1}: `//#vm-block` takes the block symbol and its id (VM_BLK_<NAME> @id <n>); got `{m.group('rest').strip()}`")
    return {"name": head.group(1), "id": int(head.group(2)), "line": i + 1, "directives": directives}


def define_value(text, macro, context):
    """The integer a `#define <macro> <n>` of the header (or a header it includes) gives."""
    m = re.search(rf"^#define\s+{re.escape(macro)}\s+([^\n/]+)", text, re.MULTILINE)
    if not m:
        fail(f"{context}: {macro} is not defined in the header")
    return safe_int(m.group(1), f"{context}: {macro}")


def enum_module():
    """The shared enum scanner (parse_members / tags), loaded once."""
    if "module" not in ENUM_MODULE:
        path = PROJECT_ROOT / "data-structures" / "auto-annotations" / "enums" / "generate-enums.py"
        spec = importlib.util.spec_from_file_location("generate_enums", path)
        ENUM_MODULE["module"] = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(ENUM_MODULE["module"])
    return ENUM_MODULE["module"]


BLOCK_ENUM_RE = re.compile(
    r"//#block-enum(?P<marker_rest>[^\n]*)\n\s*typedef\s+enum(?:\s+\w+)?\s*\{(?P<body>.*?)\}\s*(?P<name>\w+)\s*;", re.DOTALL)


def block_enums(own_text, source, context):
    """The enums a block header marks `//#block-enum [@alias <title>]` above a typedef: they belong to the block (they go into its
    content.json), not to the shared enums.json. Members follow the same rules as //#ref-enum."""
    module = enum_module()
    found = {}
    for m in BLOCK_ENUM_RE.finditer(own_text):
        members = module.parse_members(m.group("body"), module.load_sdkconfig(), f"{context}: {m.group('name')}")
        found[m.group("name")] = {"alias": module.parse_tags(m.group("marker_rest") or "").get("alias"), "source_file": source, "members": members}
    return found


def pins_from_enums(own_text, block_name, enums, context):
    """The pin entries of a block with a display.json: the members of its `vm_in_<block>_e` and `vm_out_<block>_e` enums (marked
    `//#block-enum`). A member `VM_IN_<BLOCK>_<PIN>` is input pin `<pin>` at the member's value; its trailing `//@in <tags>` comment
    (@value, @overrides, @required, ...) describes the pin. Outputs are the same with VM_OUT_ and //@out."""
    entries = []
    for side, prefix in (("in", "VM_IN_"), ("out", "VM_OUT_")):
        enum_name = f"vm_{side}_{block_name.lower()}_e"
        if enum_name not in enums:
            continue
        values = {m["name"]: m["value"] for m in enums[enum_name]["members"]}
        body = next((m.group("body") for m in BLOCK_ENUM_RE.finditer(own_text) if m.group("name") == enum_name), "")
        for line in body.splitlines():
            m = re.match(rf"^\s*(?P<const>\w+)\s*(?:=[^,/]*)?,?\s*//@{side}(?:\s+(?P<tags>.*))?$", line)
            if not m:
                if line.strip() and not line.strip().startswith("//"):
                    fail(f"{context}: {enum_name}: `{line.strip()}` needs a trailing `//@{side} @value <kind> ...` describing the pin")
                continue
            const = m.group("const")
            if not const.startswith(f"{prefix}{block_name}_"):
                fail(f"{context}: {enum_name}: {const} must be named {prefix}{block_name}_<PIN>")
            where = f"{context}: {const} //@{side}"
            lead, tags = parse_tags(m.group("tags") or "", PIN_TAGS, where)
            if lead:
                fail(f"{where}: unexpected text `{lead}` before the first tag")
            name = const[len(prefix) + len(block_name) + 1:].lower()
            index = str(values[const])
            if "repeat" in tags:  # `@repeat`: the pin repeats (any number); named `<PIN>_ANY`, valued after the numbered pins
                del tags["repeat"]
                if not name.endswith("_any"):
                    fail(f"{where}: a @repeat pin member is named {prefix}{block_name}_<PIN>_ANY")
                name, index = name[:-len("_any")], "*"
            entries.append({"side": side, "index": index, "name": name, "tags": tags, "where": where, "value": values[const]})
    for side in ("in", "out"):
        side_entries = [e for e in entries if e["side"] == side]
        numbered = [e for e in side_entries if e["index"] != "*"]
        for e in side_entries:
            if e["index"] == "*" and e["value"] != len(numbered):
                fail(f"{context}: the repeating pin `{e['name']}` is valued {e['value']}, after {len(numbered)} numbered pin(s) it must be {len(numbered)}")
    return entries


def load_enum_catalog():
    module = enum_module()
    return module.scan(module.COMPONENTS_DIR)


def load_errors():
    errors = {}
    for h in (PROJECT_ROOT / "components").rglob("*.h"):
        for name, value in ERROR_TAG_RE.findall(h.read_text(encoding="utf-8", errors="ignore")):
            errors[name] = int(value, 16)
    return errors


def load_sdkconfig():
    path = PROJECT_ROOT / "sdkconfig"
    if not path.exists():
        fail(f"{path} not found: configure the firmware once (idf.py reconfigure) so the Kconfig limits can be read")
    out = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        m = re.match(r"^(CONFIG_\w+)=(0x[0-9a-fA-F]+|-?\d+)$", line)
        if m:
            out[m.group(1)] = int(m.group(2), 0)
    return out


# ---------------------------------------------------------------------------
# State struct
# ---------------------------------------------------------------------------

def find_struct(name):
    """(body, align_attr, static_size, source path, header text) of `typedef struct ... { body } name;` under components/VM."""
    pattern = re.compile(r"typedef\s+struct\s*(?P<attr>__attribute__\s*\(\(\s*aligned\((?P<align>\d+)\)\s*\)\))?\s*\w*\s*\{(?P<body>[^{}]*)\}\s*" + re.escape(name) + r"\s*;")
    for path in sorted(VM_ROOT.rglob("*.h")):
        text = path.read_text(encoding="utf-8", errors="ignore")
        m = pattern.search(text)
        if m:
            size = re.search(r"_Static_assert\(\s*sizeof\(\s*" + re.escape(name) + r"\s*\)\s*==\s*(\d+)", text)
            return m.group("body"), int(m.group("align") or 1), int(size.group(1)) if size else None, path, text
    fail(f"state struct {name} not found under components/VM")


def layout_state(name, enums, context):
    body, attr_align, static_size, source, source_text = find_struct(name)
    if static_size is None:
        fail(f"{context}: {name} needs `_Static_assert(sizeof({name}) == N, ...)` so its layout is checked against the compiler")
    fields, offset, max_align = [], 0, attr_align
    declarations = []  # (field line, its comment): a comment-only `//` line below a field continues that field's comment
    for line in body.splitlines():
        if not line.strip():
            continue
        if line.strip().startswith("//"):
            if declarations:
                declarations[-1][1].append(line.strip()[2:].strip())
            continue
        declarations.append((line, []))
    for line, continuation in declarations:
        m = FIELD_RE.match(line)
        if not m:
            fail(f"{context}: cannot parse state field `{line.strip()}` in {name}")
        c_type = " ".join(m.group("type").split())
        types = state_types()
        if c_type not in types:
            fail(f"{context}: state field type `{c_type}` has no known size (declare it `//#vm-type {c_type} @size <n> @align <n>` where it is defined)")
        size, align = types[c_type]
        offset = (offset + align - 1) // align * align
        max_align = max(max_align, align)
        field_ctx = f"{context}.{m.group('name')}"
        comment = " ".join([m.group("comment") or "", *continuation]).strip()
        description, tags = parse_tags(comment, FIELD_TAGS, field_ctx)
        if "description" in tags:  # `@description <text>` or plain text before the first tag, not both
            if description:
                fail(f"{field_ctx}: text before the tags and @description: use one")
            description = tags.pop("description")
        field = {"name": m.group("name"), "c_type": c_type, "offset": offset}
        arr = m.group("arr")
        if arr is None:
            field["size"] = size
            offset += size
        elif arr == "":
            field["flexible"] = True
            field["element_size"] = size
        else:
            if not re.fullmatch(r"\d+|0[xX][0-9a-fA-F]+", arr):
                fail(f"{field_ctx}: array length `{arr}` must be a number")
            count = int(arr, 0)
            field.update(size=size * count, array_len=count, element_size=size)
            offset += size * count
        if description:
            field["description"] = description
        field.update(field_metadata(tags, field_ctx))
        if "enum-ref" in tags:
            if tags["enum-ref"] not in enums:
                fail(f"{field_ctx}: @enum-ref {tags['enum-ref']} is not a published //#ref-enum")
            field["enum_ref"] = tags["enum-ref"]
        # Who writes the bytes: the app from its settings (user), the app from
        # the program's layout (derived), the device (runtime, app writes 0).
        if field["name"].startswith("_"):
            field["source"] = "padding"
        elif "runtime" in tags:
            field["source"] = "runtime"
        elif "derived" in tags:
            if not tags["derived"]:
                fail(f"{field_ctx}: @derived needs the rule that computes it")
            field["source"] = "derived"
            field["derived"] = tags["derived"]
        else:
            field["source"] = "user"
        fields.append(field)
    total = (offset + max_align - 1) // max_align * max_align
    if static_size != total:
        fail(f"{context}: computed size of {name} is {total}, _Static_assert says {static_size}")
    by_name = {f["name"]: f for f in fields}
    for field_name, value in re.findall(r"_Static_assert\(\s*offsetof\(\s*" + re.escape(name) + r"\s*,\s*(\w+)\s*\)\s*==\s*(\d+)\s*,", source_text):
        if field_name not in by_name:
            fail(f"{context}: _Static_assert(offsetof({name}, {field_name})) names no field")
        if by_name[field_name]["offset"] != int(value):
            fail(f"{context}: {name}.{field_name} computes to offset {by_name[field_name]['offset']}, _Static_assert says {value}")
    return {"struct": name, "source_file": source.relative_to(PROJECT_ROOT).as_posix(), "size": total, "align": max_align, "fields": fields}


def field_metadata(tags, context):
    """Editor metadata of a state field or a pin (`@id`, `@device-field`, ...), checked for shape."""
    metadata = {}
    if "id" in tags:
        if tags["id"] not in ("device", "pin"):
            fail(f"{context}: @id must be device or pin")
        metadata["id_kind"] = tags["id"]
    for tag in ("device-field", "contract", "let-user-select-available"):
        if tag in tags:
            if not IDENT_RE.match(tags[tag]):
                fail(f"{context}: @{tag} needs one identifier")
            metadata[tag.replace("-", "_")] = tags[tag]
    if "hidden-by-default" in tags:
        metadata["hidden_by_default"] = True
    if "dynamic-input" in tags:
        if not re.fullmatch(r"\d+", tags["dynamic-input"]):
            fail(f"{context}: @dynamic-input needs an input index")
        metadata["dynamic_input"] = int(tags["dynamic-input"])
    return metadata


# ---------------------------------------------------------------------------
# Pins
# ---------------------------------------------------------------------------

def parse_pins(entries, text, sdkconfig, context):
    """(inputs, outputs, shape) from the //@in and //@out lines, checked against the header's index macros.

    The shape the firmware enforces at load comes from here: `@required` marks a pin the block cannot run
    without (a numbered input also goes into required_in), min_in / min_q reach the highest required
    pin (a required `*` pin asks for one more than the numbered ones), max_in / max_q are the numbered
    pins, or the Kconfig limit when a `*` pin is listed."""
    pins = {"in": [], "out": []}
    for entry in entries:
        where, index, name, tags = entry["where"], entry["index"], entry["name"], entry["tags"]
        if "title" not in tags or not tags["title"]:
            fail(f"{where}: needs @title")
        if tags.get("value") not in VALUE_KINDS:
            fail(f"{where}: needs @value, one of {sorted(VALUE_KINDS)}")
        pin = {"index": "*" if index == "*" else int(index), "name": name, "title": tags["title"], "value": tags["value"]}
        if "description" in tags:
            if not tags["description"]:
                fail(f"{where}: @description is empty")
            pin["description"] = tags["description"]
        pin.update(field_metadata({k: v for k, v in tags.items() if k in ("id", "device-field", "hidden-by-default")}, where))
        pin["_required"] = "required" in tags
        if "overrides" in tags:
            if not IDENT_RE.match(tags["overrides"]):
                fail(f"{where}: @overrides needs one state field name")
            pin["overrides"] = tags["overrides"]
        pin["_where"] = where
        pins[entry["side"]].append(pin)

    names = [p["name"] for side in pins.values() for p in side]
    for name in sorted({n for n in names if names.count(n) > 1}):
        fail(f"{context}: pin name `{name}` is used twice (pin names are unique across the block so {{{name}}} is unambiguous)")

    shape = {}
    for side, limit_key, min_key, max_key in (("in", "CONFIG_VM_BLOCK_MAX_IN", "min_in", "max_in"), ("out", "CONFIG_VM_BLOCK_MAX_OUT", "min_q", "max_q")):
        listed = pins[side]
        required_numbered = [p["index"] for p in listed if p["index"] != "*" and p["_required"]]
        star_required = any(p["index"] == "*" and p["_required"] for p in listed)
        numbered_count = sum(1 for p in listed if p["index"] != "*")
        minimum = (max(required_numbered) + 1 if required_numbered else 0)
        if star_required:
            minimum = max(minimum, numbered_count + 1)
        shape[min_key] = minimum
        shape[max_key] = limit_key if any(p["index"] == "*" for p in listed) else numbered_count
        numbered = sorted(p["index"] for p in listed if p["index"] != "*")
        stars = [p for p in listed if p["index"] == "*"]
        if len(numbered) != len(set(numbered)):
            fail(f"{context}: two //@{side} lines share an index")
        if len(stars) > 1:
            fail(f"{context}: at most one `*` //@{side} line")
        if numbered != list(range(len(numbered))):
            missing = sorted(set(range(numbered[-1] + 1)) - set(numbered)) if numbered else []
            fail(f"{context}: //@{side} indexes must run 0..{len(numbered) - 1} without gaps (missing {missing or 'a start at 0'})")
        if numbered and numbered[-1] >= sdkconfig[limit_key]:
            fail(f"{context}: //@{side} {numbered[-1]} is past {limit_key} ({sdkconfig[limit_key]})")
        if stars and listed.index(stars[0]) != len(listed) - 1:
            fail(f"{context}: the `*` //@{side} line must come last")
    required = 0
    for pin in pins["in"]:
        if pin["index"] != "*" and pin["_required"]:
            required |= 1 << pin["index"]
    shape["required_in"] = required
    for pin in pins["in"]:
        pin["required"] = pin["index"] != "*" and pin["_required"]
    return pins["in"], pins["out"], shape


def link_overrides(inputs, fields, context):
    """Tie each `@overrides` pin to its state field: the field is the constant used while the pin is unwired, so the pin starts hidden."""
    by_name = {f["name"]: f for f in fields}
    for pin in inputs:
        target = pin.get("overrides")
        if not target:
            continue
        where = pin["_where"]
        field = by_name.get(target)
        if not field or field["source"] != "user" or field.get("flexible"):
            fail(f"{where}: @overrides {target} must name a user state field of the block")
        if field["c_type"] not in OVERRIDE_TYPES.get(pin["value"], set()):
            fail(f"{where}: @overrides {target} is a {field['c_type']}, which a {pin['value']} pin cannot replace")
        if "overridden_by" in field:
            fail(f"{where}: {target} is already overridden by another pin")
        if pin["index"] == "*":
            fail(f"{where}: a `*` pin cannot override one field")
        if pin["required"]:
            fail(f"{where}: a required input cannot have a constant to fall back on")
        field["overridden_by"] = pin["index"]
        pin["hidden_by_default"] = True


def validate_editor_links(block, context):
    fields = {field["name"]: field for field in block.get("state", {}).get("fields", [])}
    pins = block["inputs"]["pins"]
    dynamic_targets = {f["dynamic_input"] for f in fields.values() if "dynamic_input" in f}
    for entry in [*fields.values(), *pins, *block["outputs"]["pins"]]:
        device = entry.get("device_field")
        if device and fields.get(device, {}).get("id_kind") != "device":
            fail(f"{context}.{entry['name']}: @device-field {device} must name a device ID field")
        if entry.get("id_kind") == "pin" and not device:
            fail(f"{context}.{entry['name']}: a pin ID needs @device-field")
        if entry.get("hidden_by_default") and entry.get("required"):
            fail(f"{context}.{entry['name']}: a required input cannot be hidden by default")
        selection = entry.get("let_user_select_available")
        if selection:
            if fields.get(selection, {}).get("id_kind") != "pin" or entry.get("c_type") != "uint64_t":
                fail(f"{context}.{entry['name']}: a selectable mask must be uint64_t and name a pin ID field")
            if not any(pin["index"] == entry.get("dynamic_input") and pin.get("hidden_by_default") for pin in pins):
                fail(f"{context}.{entry['name']}: @dynamic-input must name a hidden optional input")
    for pin in pins:
        if pin.get("hidden_by_default") and not pin.get("overrides") and pin["index"] not in dynamic_targets:
            fail(f"{context}.{pin['name']}: a hidden input needs `@overrides <field>` (the constant to use) or a mask field with @dynamic-input {pin['index']}; otherwise nothing can set it")


def pin_group(minimum, pins, limit_key, sdkconfig):
    """min / max counts of a pin direction: numbered pins cap it, a `*` pin lets it grow to the Kconfig limit."""
    limit = sdkconfig[limit_key]
    numbered = [p["index"] for p in pins if p["index"] != "*"]
    star = any(p["index"] == "*" for p in pins)
    maximum = limit if star else (max(numbered) + 1 if numbered else 0)
    group = {"min": minimum, "max": maximum}
    if star:
        group["max_symbol"] = limit_key
    group["pins"] = [{k: v for k, v in pin.items() if not k.startswith("_")} for pin in pins]
    return group


# ---------------------------------------------------------------------------
# Face: the header template
# ---------------------------------------------------------------------------

def resolve_ref(name, scope, context):
    if name == "title":
        return {"ref": name, "kind": "title"}
    pin = scope["inputs"].get(name)
    field = scope["fields"].get(name)
    if pin is not None:
        if field is not None and pin.get("overrides") != name:
            fail(f"{context}: {{{name}}} is both an input pin and a state field; add `@overrides {name}` to the pin or rename one")
        if pin["index"] == "*":
            fail(f"{context}: {{{name}}} is a repeating pin and cannot be referenced")
        part = {"ref": name, "kind": "pin", "pin": pin["index"]}
        if pin.get("overrides"):
            part["field"] = pin["overrides"]
        return part
    if name in scope["outputs"]:
        pin = scope["outputs"][name]
        if pin["index"] == "*":
            fail(f"{context}: {{{name}}} is a repeating pin and cannot be referenced")
        return {"ref": name, "kind": "out", "pin": pin["index"]}
    if field is not None:
        if field["source"] != "user" or field.get("flexible"):
            fail(f"{context}: {{{name}}} is not a setting the user enters (state field source {field['source']})")
        return {"ref": name, "kind": "field", "field": name}
    known = sorted({"title", *scope["inputs"], *scope["outputs"], *(n for n, f in scope["fields"].items() if f["source"] == "user")})
    fail(f"{context}: {{{name}}} names no pin or setting (known: {', '.join(known)})")


def parse_template(text, scope, context):
    """A line of text with `{ref}`s as parts: `{"text": ..}` and `{"ref": ..., "kind": ...}`."""
    parts, pos = [], 0
    for m in REF_RE.finditer(text):
        if m.start() > pos:
            parts.append({"text": text[pos:m.start()]})
        parts.append(resolve_ref(m.group(1), scope, context))
        pos = m.end()
    if pos < len(text):
        parts.append({"text": text[pos:]})
    for part in parts:
        if "text" in part and ("{" in part["text"] or "}" in part["text"]):
            fail(f"{context}: stray brace in `{text}` (a reference is {{name}} with a known name)")
    if parts and "text" in parts[0]:
        parts[0]["text"] = parts[0]["text"].lstrip()
    if parts and "text" in parts[-1]:
        parts[-1]["text"] = parts[-1]["text"].rstrip()
    parts = [p for p in parts if "ref" in p or p["text"]]
    if not parts:
        fail(f"{context}: empty template")
    return parts


def build_header(text, inputs, outputs, fields, context):
    """The block face's line under the title (`<lead> | <value>`), or None."""
    if not text:
        return None
    scope = {"inputs": {p["name"]: p for p in inputs}, "outputs": {p["name"]: p for p in outputs}, "fields": {f["name"]: f for f in fields}}
    where = f"{context}: header"
    lead, _, value = text.partition("|")
    header = {"lead": parse_template(lead, scope, where)}
    if value.strip():
        header["value"] = parse_template(value, scope, where)
    return header


# ---------------------------------------------------------------------------
# Bytecode encoding (EXPR / EXPR_BIT)
# ---------------------------------------------------------------------------

def opcode_table(text, enum_name, catalog, context):
    m = re.search(OPTABLE_RE.format(enum=re.escape(enum_name)), text, re.DOTALL)
    if not m:
        fail(f"{context}: @opcodes {enum_name} but no //#vm-opcodes {enum_name} table in the header")
    entries = {e.group("sym"): e for e in OPENTRY_RE.finditer(m.group("body"))}
    if enum_name not in catalog["enums"]:
        fail(f"{context}: {enum_name} is not a published //#ref-enum")
    ops = []
    for member in catalog["enums"][enum_name]["members"]:
        if member["name"].endswith("_CNT"):  # the count sentinel
            continue
        e = entries.get(member["name"])
        if not e:
            fail(f"{context}: opcode {member['name']} has no entry in the //#vm-opcodes table")
        ops.append({"symbol": member["name"], "value": member["value"], "alias": member["alias"], "description": member["description"],
                    "pops": int(e.group("pops")), "pushes": int(e.group("pushes")), "operand": ARG_KINDS[e.group("arg")]})
    extra = set(entries) - {o["symbol"] for o in ops}
    if extra:
        fail(f"{context}: //#vm-opcodes table names non-members {sorted(extra)}")
    return ops


def check_code(code, ops, in_cnt, const_cnt, stack_max):
    """The block's load-time bytecode check, for the examples."""
    by_value = {o["value"]: o for o in ops}
    sp, pc = 0, 0
    while pc < len(code):
        op = by_value.get(code[pc])
        if op is None:
            return f"unknown opcode {code[pc]} at {pc}"
        pc += 1
        if op["value"] == 0:
            break
        if op["operand"] != "none":
            if pc >= len(code):
                return f"{op['symbol']} at {pc - 1} has no operand"
            arg = code[pc]
            pc += 1
            if arg >= (in_cnt if op["operand"] == "input" else const_cnt):
                return f"{op['symbol']} operand {arg} out of range"
        if sp < op["pops"]:
            return f"{op['symbol']} underflows the stack"
        sp = sp - op["pops"] + op["pushes"]
        if sp > stack_max:
            return f"{op['symbol']} overflows the stack"
    return None if sp == 1 else f"stack ends with {sp} values"


def number_list(text):
    return [t.strip() for t in text.split(",") if t.strip()]


def constant(value, const_type, what):
    try:
        return float(value) if const_type == "f32" else int(value, 0)
    except ValueError:
        fail(f"{what}: `{value}` is not a {'number' if const_type == 'f32' else 'whole number'}")


def build_examples(directives, ops, const_type, stack_max, state, context):
    """Golden custom_data for each //@example: the state header is written into the computed layout, then constants, then code."""
    fields = {f["name"]: f for f in state["fields"]}
    for needed, width in (("const_cnt", 1), ("code_len", 2)):
        if needed not in fields or fields[needed].get("size") != width:
            fail(f"{context}: a bytecode block's state struct needs a {width}-byte `{needed}` field")
    symbols = {o["symbol"]: o for o in ops}
    out = []
    for d in directives:
        if d["keyword"] != "example":
            continue
        where = f"{context}: //@example (line {d['line']})"
        title, tags = parse_tags(d["rest"], EXAMPLE_TAGS, where)
        if not title or "result" not in tags or "code" not in tags:
            fail(f"{where}: needs a title, @code and @result")
        inputs = [constant(v, const_type, where) for v in number_list(tags.get("in", ""))]
        consts = [constant(v, const_type, where) for v in number_list(tags.get("consts", ""))]
        code, tokens, i = [], tags["code"].split(), 0
        while i < len(tokens):
            op = symbols.get(tokens[i])
            if not op:
                fail(f"{where}: unknown opcode {tokens[i]}")
            code.append(op["value"])
            i += 1
            if op["operand"] != "none":
                if i >= len(tokens):
                    fail(f"{where}: {op['symbol']} needs an operand")
                operand = constant(tokens[i], "u32", where)
                if not 0 <= operand < 256:
                    fail(f"{where}: operand {operand} does not fit a byte")
                code.append(operand)
                i += 1
        problem = check_code(code, ops, len(inputs), len(consts), stack_max)
        if problem:
            fail(f"{where}: `{title}` would be refused at load: {problem}")
        packed = b"".join(struct.pack("<f", c) if const_type == "f32" else struct.pack("<I", c) for c in consts)
        head = bytearray(state["size"])
        head[fields["const_cnt"]["offset"]] = len(consts)
        head[fields["code_len"]["offset"]:fields["code_len"]["offset"] + 2] = struct.pack("<H", len(code))
        custom = bytes(head) + packed + bytes(code)
        out.append({
            "title": title, "inputs": inputs, "constants": consts, "code": tokens,
            "custom_data": custom.hex(), "custom_len": len(custom),
            "result": constant(tags["result"], const_type, where),
        })
    return out


def bytecode_encoding(text, opcodes_enum, stack_macro, directives, inputs, state, catalog, context):
    ops = opcode_table(text, opcodes_enum, catalog, context)
    stack_max = define_value(text, stack_macro, context)
    star = next((p for p in inputs if p["index"] == "*"), None)
    const_type = star["value"] if star else "f32"
    if const_type not in ("f32", "u32"):
        fail(f"{context}: a bytecode block's repeating input must be f32 or u32 (its constants take that type), not {const_type}")
    return {
        "kind": "bytecode",
        "layout": f"state header, then const_cnt constants of 4 bytes, then code_len code bytes; custom_len = {state['size']} + 4 x const_cnt + code_len",
        "constant_type": const_type,
        "stack_max": stack_max,
        "opcode_enum": opcodes_enum,
        "opcodes": ops,
        "examples": build_examples(directives, ops, const_type, stack_max, state, context),
    }


# ---------------------------------------------------------------------------
# Documents
# ---------------------------------------------------------------------------

def one(directives, keyword):
    found = [d for d in directives if d["keyword"] == keyword]
    return found[0] if found else None


DISPLAY_KEYS = {"title", "category", "description", "activation", "header", "always_detailed", "eno", "inputs", "outputs"}
DISPLAY_PIN_KEYS = {"title", "description"}


def read_display(path, context):
    """`<name>.display.json` next to the header, written by hand: what the editor shows (title, category, description, the activation
    text, the face line `header`, a title and description for each pin by pin name, `eno`, `always_detailed`). The block's
    `<name>.content.json` is generated from the header."""
    stem = path.parent / path.name[len("vm_block_"):-len(".h")]
    source = Path(f"{stem}.display.json")
    if not source.exists():
        fail(f"{context}: needs {source.name} next to the header (the title, category, description and pin titles of the block)")
    DISPLAY_FILES[path] = (source.relative_to(PROJECT_ROOT).as_posix(), Path(f"{stem}.content.json").relative_to(PROJECT_ROOT).as_posix())
    doc = json.loads(source.read_text(encoding="utf-8"))
    unknown = sorted(set(doc) - DISPLAY_KEYS)
    if unknown:
        fail(f"{source.name}: {context}: unknown key {unknown} (known: {sorted(DISPLAY_KEYS)})")
    for side in ("inputs", "outputs"):
        for pin, shown in doc.get(side, {}).items():
            extra = sorted(set(shown) - DISPLAY_PIN_KEYS)
            if extra:
                fail(f"{source.name}: {context}: {side} `{pin}`: unknown key {extra} (known: {sorted(DISPLAY_PIN_KEYS)})")
    for key in ("title", "category", "description"):
        if not doc.get(key):
            fail(f"{source.name}: {context}: needs `{key}`")
    return doc


def apply_display_to_pins(pins, display, context):
    """Give each pin the title and description its display.json lists by pin name; a pin without a title, or a listed name with no pin, is an error."""
    for pin in pins:
        if {"title", "description"} & set(pin["tags"]):
            fail(f"{pin['where']}: @title and @description belong in the display.json")
        shown = display.get({"in": "inputs", "out": "outputs"}[pin["side"]], {}).get(pin["name"])
        if not shown or not shown.get("title"):
            fail(f"{pin['where']}: the display.json needs a title for pin `{pin['name']}`")
        pin["tags"].update({k: v for k, v in shown.items() if v})
    for side, key in (("in", "inputs"), ("out", "outputs")):
        known = {p["name"] for p in pins if p["side"] == side}
        for name in display.get(key, {}):
            if name not in known:
                fail(f"{context}: the display.json has {key} `{name}`, the header has no such pin")
    return pins


def spec_from_directives(directives, display, own_text, name, enums, context):
    """The block's face and shape: the structure from the header's //@ lines and pin enums, the face from its display.json."""
    for keyword, times in DIRECTIVES.items():
        count = sum(1 for d in directives if d["keyword"] == keyword)
        if times == "one" and count > 1:
            fail(f"{context}: //@{keyword} given {count} times")
    for keyword in REQUIRED_DIRECTIVES:
        if not one(directives, keyword):
            fail(f"{context}: needs //@{keyword}")
    kind = one(directives, "activation")["rest"].strip()
    enables, header = one(directives, "enables"), display.get("header")
    rules = []
    for d in directives:
        if d["keyword"] == "rule":
            rule_text, tags = parse_tags(d["rest"], RULE_TAGS, f"{context}: //@rule (line {d['line']})")
            rules.append({"rule": rule_text, "error": tags.get("error")})
    pins = apply_display_to_pins(pins_from_enums(own_text, name, enums, context), display, context)
    return {"title": display["title"], "category": display["category"], "description": display["description"],
            "activation_kind": kind, "activation_text": display.get("activation", ""), "header": header,
            "enables": enables["rest"] if enables else None, "always_detailed": bool(display.get("always_detailed")),
            "eno": display.get("eno"), "rules": rules, "pins": pins,
            "data": one(directives, "data")["rest"] if one(directives, "data") else None}


def build_block(path, text, source, catalog, errors, sdkconfig):
    enums = catalog["enums"]
    name = source["name"]
    context = f"{path.name}: VM_BLK_{name}"
    if not 1 <= source["id"] <= 255:
        fail(f"{context}: @id {source['id']} must be 1 to 255 (block_type is one byte; 0 is reserved for 'not set')")
    directives = source["directives"]
    display = read_display(path, context)
    own_text = path.read_text(encoding="utf-8").replace("\r\n", "\n")
    own = block_enums(own_text, path.relative_to(PROJECT_ROOT).as_posix(), context)
    enums = {**enums, **own}
    spec = spec_from_directives(directives, display, own_text, name, enums, context)
    DISPLAY_BLOCKS[name] = DISPLAY_FILES[path]
    title, category, description, kind = spec["title"], spec["category"], spec["description"], spec["activation_kind"]
    if not title or not category or not re.fullmatch(r"[a-z][a-z0-9_-]*", category):
        fail(f"{context}: needs a title and a category of one lowercase word")
    if kind not in ACTIVATION_KINDS:
        fail(f"{context}: the activation must be one of {sorted(ACTIVATION_KINDS)}, got {kind}")
    if not description:
        fail(f"{context}: needs a description")
    if one(directives, "data-tail") and not spec["data"]:
        fail(f"{context}: //@data-tail needs //@data")
    opcodes_enum = stack_macro = None
    if one(directives, "opcodes"):
        opcodes_enum, tags = parse_tags(one(directives, "opcodes")["rest"], {"stack-max"}, f"{context}: //@opcodes")
        stack_macro = tags.get("stack-max")
        if not IDENT_RE.match(opcodes_enum) or not stack_macro:
            fail(f"{context}: //@opcodes <enum> @stack-max <C macro>: the opcode enum and the macro with the evaluator's stack depth")
    if opcodes_enum and not spec["data"]:
        fail(f"{context}: //@opcodes needs //@data (the header struct)")

    inputs, outputs, shape = parse_pins(spec["pins"], text, sdkconfig, context)
    enables = spec["enables"]
    if enables not in (None, "required", "optional"):
        fail(f"{context}: enables is `required` (at least one enable source) or `optional`, got `{enables}`")
    shape["min_en"] = 1 if enables == "required" else 0
    lower = name.lower()
    if not re.search(rf"\bvm_blk_{lower}\s*\(", text):
        fail(f"{context}: the header must declare the body `void vm_blk_{lower}(vm_block_h b);`")
    C_INFO[name] = {"shape": shape, "has_check": bool(re.search(rf"\bvm_verify_{lower}\s*\(", text)), "struct": None}
    state = None
    if spec["data"]:
        state = layout_state(spec["data"], enums, context)
        C_INFO[name]["struct"] = spec["data"]
        if one(directives, "data-tail"):
            state["tail"] = one(directives, "data-tail")["rest"]
    fields = state["fields"] if state else []
    link_overrides(inputs, fields, context)
    header = build_header(spec["header"], inputs, outputs, fields, context)

    rules = []
    for rule in spec["rules"]:
        if not rule.get("rule") or rule.get("error") not in errors:
            fail(f"{context}: a rule needs text and an existing error (got {rule.get('error')})")
        rules.append({"rule": rule["rule"], "error": rule["error"], "error_tag": errors[rule["error"]]})

    block = {
        "$schema": BLOCK_SCHEMA.relative_to(PROJECT_ROOT).as_posix(),
        "schemaVersion": 1,
        "kind": "vm-block",
        "id": source["id"],
        "name": f"VM_BLK_{name}",
        "title": title,
        "category": category,
        "description": description,
        "source_file": path.relative_to(PROJECT_ROOT).as_posix(),
        "activation": {"kind": kind, "description": spec["activation_text"].strip() or ACTIVATION_KINDS[kind]},
        "inputs": pin_group(shape["min_in"], inputs, "CONFIG_VM_BLOCK_MAX_IN", sdkconfig),
        "outputs": pin_group(shape["min_q"], outputs, "CONFIG_VM_BLOCK_MAX_OUT", sdkconfig),
        "rules": rules,
    }
    if spec["eno"]:
        if not spec["eno"].get("title"):
            fail(f"{context}: eno needs a title")
        block["eno"] = spec["eno"]
    if header:
        block["header"] = header
    if spec["always_detailed"]:
        if not any(pin.get("overrides") for pin in inputs) and not opcodes_enum:
            fail(f"{context}: always-detailed needs an @overrides input or @opcodes: nothing else is in the detailed view")
        block["always_detailed"] = True
    if state:
        block["state"] = state
    block["min_custom_len"] = state["size"] if state else 0
    if opcodes_enum:
        block["encoding"] = bytecode_encoding(text, opcodes_enum, stack_macro, directives, inputs, state, catalog, context)
    used = sorted({f["enum_ref"] for f in fields if "enum_ref" in f} | ({opcodes_enum} if opcodes_enum else set()) | set(own))
    block["enums"] = {e: enums[e] for e in used}
    validate_editor_links(block, context)
    return block


def build():
    catalog = load_enum_catalog()
    errors = load_errors()
    sdkconfig = load_sdkconfig()
    blocks = []
    for path in sorted(BLOCKS_DIR.glob("*/vm_block_*.h")):
        own = path.read_text(encoding="utf-8").replace("\r\n", "\n")
        source = scan_block(path.name, own)
        if source is None:
            fail(f"{path.relative_to(PROJECT_ROOT).as_posix()}: a vm_block_*.h needs its `//#vm-block VM_BLK_<NAME> @id <n>` line (shared code goes in a folder whose header is not named vm_block_*)")
        blocks.append(build_block(path, read_header(path, own), source, catalog, errors, sdkconfig))
    seen = {}
    for block in blocks:
        if block["name"] in seen:
            fail(f"{block['name']} has two //#vm-block directive blocks ({seen[block['name']]} and {block['source_file']})")
        seen[block["name"]] = block["source_file"]
    by_id = {}
    for block in blocks:
        if block["id"] in by_id:
            fail(f"{block['name']} and {by_id[block['id']]} both have @id {block['id']} ({block['source_file']})")
        by_id[block["id"]] = block["name"]
    blocks.sort(key=lambda b: b["id"])
    index = {
        "$schema": INDEX_SCHEMA.relative_to(PROJECT_ROOT).as_posix(),
        "schemaVersion": 1,
        "kind": "vm-blocks-index",
        "common_rules": [
            "in_cnt and q_cnt are at least the block's inputs.min / outputs.min, and at most its max.",
            "Every required input is wired (not VM_BLOCK_NO_ID).",
            "custom_len is at least the state size.",
        ],
        "common_rules_error": "ERR_VM_BLK_BAD_SHAPE",
        "value_kinds": VALUE_KINDS,
        "activation_kinds": ACTIVATION_KINDS,
        "id_kinds": ID_KINDS,
        "blocks": [{"id": b["id"], "name": b["name"], "title": b["title"], "category": b["category"], **block_files(b)} for b in blocks],
    }
    return blocks, index


def read_header(path, own):
    """The block header's text plus the block headers it includes, one level: opcode tables, index macros and shared types may live there."""
    extra = []
    for name in INCLUDE_RE.findall(own):
        extra += [c.read_text(encoding="utf-8").replace("\r\n", "\n") for c in sorted(BLOCKS_DIR.glob(f"*/{name}")) if c != path]
    return own + "\n" + "\n".join(extra)


def content_of(block):
    """The block without what the display.json owns: the face, the pin titles and descriptions. The app builds the block from the
    two files by pin and field name."""
    content = {k: v for k, v in block.items() if k not in ("$schema", "title", "category", "description", "header", "eno", "always_detailed")}
    content["kind"] = "vm-block-content"
    content["activation"] = {"kind": block["activation"]["kind"]}
    content["min_enables"] = C_INFO[block["name"][len("VM_BLK_"):]]["shape"]["min_en"]
    for side in ("inputs", "outputs"):
        content[side] = {**block[side], "pins": [{k: v for k, v in p.items() if k not in ("title", "description")} for p in block[side]["pins"]]}
    return content


def block_files(block):
    """Where the app finds a block: the two files in its folder."""
    display, content = DISPLAY_BLOCKS[block["name"][len("VM_BLK_"):]]
    return {"display": display, "content": content}


def validate(document, schema_path, label):
    if jsonschema is None:
        fail("the jsonschema package is required to check the generated files (pip install jsonschema), or pass --skip-schema")
    schema = json.loads(schema_path.read_text(encoding="utf-8"))
    problems = sorted(jsonschema.Draft202012Validator(schema).iter_errors(document), key=lambda e: list(e.path))
    if problems:
        fail(f"{label} failed schema validation:\n" + "\n".join(f"  - at {'/'.join(map(str, e.path)) or '<root>'}: {e.message}" for e in problems))


def render_ids(blocks):
    lines = [C_GENERATED_MARK, "#pragma once", "",
             "/* The palette ids: the @id of every //#vm-block. The id is the index into g_vm_block_types[] (blocks/vm_blocks_table.c)",
             "   and the block_type byte on the wire, so a number is never reused for another block. */", "",
             "#define VM_BLK_NONE 0  // reserved: an unset block_type is not runnable"]
    for b in blocks:
        lines.append(f"#define {b['name']} {b['id']}  // {b['title']} -- {Path(b['source_file']).name}")
    return ("\n".join(lines) + "\n").encode("utf-8")


def c_entry(block):
    """The palette table entry of a block: body, check, pin shape and state size, all from its //#vm-block directives."""
    name = block["name"][len("VM_BLK_"):]
    info, lower = C_INFO[name], name.lower()
    shape = info["shape"]
    fields = [f".run = vm_blk_{lower}"]
    if info["has_check"]:
        fields.append(f".check = vm_verify_{lower}")
    fields += [f".min_in = {shape['min_in']}", f".max_in = {shape['max_in']}", f".min_q = {shape['min_q']}", f".max_q = {shape['max_q']}",
               f".min_en = {shape['min_en']}", f".required_in = 0x{shape['required_in']:X}u",
               f".state_len = {'sizeof(' + info['struct'] + ')' if info['struct'] else '0'}"]
    return f"  [{block['name']}] = {{" + ", ".join(fields) + "},"


def render_registry(blocks):
    headers = sorted({Path(b["source_file"]).name for b in blocks})
    lines = [C_GENERATED_MARK, "#pragma once", "",
             "/* Included by blocks/vm_blocks_table.c only: every block header, and the palette entries by id. An entry is the",
             "   block's body and check (by name: vm_blk_<name>, vm_verify_<name>), the pin shape its //@in / //@out / //@enables",
             "   directives declare (vm_block_verify() enforces it at load) and the size of its state struct. */", ""]
    lines += [f'#include "{h}"' for h in headers]
    lines += ["", "#define VM_BLOCK_TABLE_ENTRIES \\"]
    entries = [c_entry(b) for b in blocks]
    lines += [e + " \\" for e in entries[:-1]] + [entries[-1]]
    return ("\n".join(lines) + "\n").encode("utf-8")


def guide_outputs(block):
    """The user guide of a block: `<name>.md` next to its header and its `images/` become app/docs/blocks/<name>.md and
    images/<name>/. The text is the author's own and is not checked against the C: a plain copy."""
    header = PROJECT_ROOT / block["source_file"]
    name = block["name"][len("VM_BLK_"):].lower()
    source = header.parent / f"{name}.md"
    if not source.exists():
        return []
    text = source.read_text(encoding="utf-8").replace("\r\n", "\n")
    text = GUIDE_IMAGE_RE.sub(lambda m: f"{m.group(1)}images/{name}/", text)
    outputs = [(GUIDE_DIR / f"{name}.md", f"{GUIDE_MARK} {source.relative_to(PROJECT_ROOT).as_posix()} - do not edit. -->\n\n{text}".encode("utf-8"))]
    images = source.parent / "images"
    if images.is_dir():
        outputs.extend((GUIDE_DIR / "images" / name / image.name, image.read_bytes().replace(b"\r\n", b"\n")) for image in sorted(images.iterdir()) if image.is_file())
    return outputs


def render(document):
    return (json.dumps(document, indent=2) + "\n").encode("utf-8")


def main(argv):
    check, skip_schema = "--check" in argv, "--skip-schema" in argv
    blocks, index = build()
    if not skip_schema:
        for block in blocks:
            validate(block, BLOCK_SCHEMA, block["name"])
        validate(index, INDEX_SCHEMA, "index")
    outputs = {PROJECT_ROOT / DISPLAY_BLOCKS[b["name"][len("VM_BLK_"):]][1]: render(content_of(b)) for b in blocks}
    outputs[OUT_DIR / "index.generated.json"] = render(index)
    outputs[IDS_HEADER] = render_ids(blocks)
    outputs[REGISTRY_HEADER] = render_registry(blocks)
    for block in blocks:
        outputs.update(dict(guide_outputs(block)))
    stale = [p for p in OUT_DIR.glob("*.generated.json") if p not in outputs] if OUT_DIR.exists() else []
    if check:
        # A Windows checkout may hold CRLF: compare the text, not the line endings.
        def current(path):
            return path.read_bytes().replace(b"\r\n", b"\n")

        wrong = [p.name for p, content in outputs.items() if not p.exists() or current(p) != content] + [f"{p.name} (no such block)" for p in stale]
        if wrong:
            print("Out of date: " + ", ".join(wrong) + "\nRun: python data-structures/auto-annotations/generate-all.py")
            return 1
        print(f"{OUT_DIR.relative_to(PROJECT_ROOT)} is up to date ({len(blocks)} blocks + index, id and registry headers)")
        return 0
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for path in stale:
        path.unlink()  # a block that no longer exists
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)  # LF on every platform, so the files diff the same everywhere
    print(f"Wrote {OUT_DIR.relative_to(PROJECT_ROOT)} ({len(blocks)} blocks + index) and the id and registry headers in {BLOCKS_DIR.relative_to(PROJECT_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
