#pragma once

#define I2C_OWNER_MAP(X) \
    X(OWNER_MANAGER_I2C,     0xc000, "I2C_MANAGER") \
    X(OWNER_I2C_BUS_0,       0xc001, "I2C_BUS_0") \
    X(OWNER_I2C_BUS_1,       0xc002, "I2C_BUS_1") \
    X(OWNER_I2C_DEVICE_TASK, 0xc003, "I2C_DEVICE_TASK")\
    X(OWNER_I2C_ADD_DRIVER,  0xc004, "I2C_ADD_DRIVER")

#define I2C_ERROR_MAP(X) \
    X(ERR_I2C_BASE,              0xC000, "I2C_BASE_FAULT") \
    X(ERR_I2C_DEV_ADDR_CONFLICT, 0xC001, "I2C_DEVICE_ADDRESS_CONFLICT") \
    X(ERR_I2C_DEV_REG_FULL,      0xC002, "I2C_DEVICE_REGISTRY_FULL")\
    X(ERR_I2C_DEV_NOT_FOUND,     0xC003, "I2C_DEVICE_NOT_FOUND")\
    X(ERR_I2C_BUS_FAILURE,       0xC004, "I2C_BUS_FAILURE")\
    X(ERR_I2C_TIMEOUT,           0xC005, "I2C_TIMEOUT")\
    X(ERR_I2C_TRANSMISSION_FAILURE, 0xC006, "I2C_TRANSMISSION_FAILURE")\
    X(ERR_I2C_FEATURE_UNSUPPORTED, 0xC007, "I2C_FEATURE_UNSUPPORTED")\
    X(ERR_I2C_INVALID_PARAM,      0xC008, "I2C_INVALID_PARAM")\
    X(ERR_I2C_NOT_CONNECTED,        0xC009, "I2C_NOT_CONNECTED")

