#pragma once


// Move GPIO expander owner and error IDs to D100.. range to avoid overlaps
#define PROVIDER_GPIO_EXPANDER_OWNER_MAP(X) \
    X(OWNER_PROVIDER_GPIO_EXPANDER_INIT, 0xD101, "OWNER_PROVIDER_GPIO_EXPANDER_INIT")\
    X(OWNER_PROVIDER_GPIO_EXPANDER_SET_PINS, 0xD102, "OWNER_PROVIDER_GPIO_EXPANDER_SET_PINS")\
    X(OWNER_PROVIDER_GPIO_EXPANDER_READ_PINS, 0xD103, "OWNER_PROVIDER_GPIO_EXPANDER_READ_PINS")\
    X(OWNER_PROVIDER_GPIO_EXPANDER_TOGGLE_PINS, 0xD104, "OWNER_PROVIDER_GPIO_EXPANDER_TOGGLE_PINS")\
    X(OWNER_PROVIDER_GPIO_EXPANDER_SET_CALLBACK, 0xD105, "OWNER_PROVIDER_GPIO_EXPANDER_SET_CALLBACK")\
    X(OWNER_PROVIDER_GPIO_EXPANDER_CONFIGURE_PINS, 0xD106, "OWNER_PROVIDER_GPIO_EXPANDER_CONFIGURE_PINS")

#define PROVIDER_GPIO_EXPANDER_ERROR_MAP(X) \
    X(ERR_PROVIDER_GPIO_EXPANDER_BASE, 0xD100, "ERR_PROVIDER_GPIO_EXPANDER_BASE")\
    X(EXPANDER_INVALID_PIN, 0xD101, "EXPANDER_INVALID_PIN")\
    X(EXPANDER_UNSUPPORTED_MODE, 0xD102, "EXPANDER_UNSUPPORTED_MODE")\
    X(EXPANDER_UPDATE_FAILED, 0xD103, "EXPANDER_UPDATE_FAILED")

