#pragma once

#define PROVIDER_GPIO_EXPANDER_OWNER_MAP(X) \
    X(OWNER_PROVIDER_GPIO_EXPANDER_INIT, 0xD001, "OWNER_PROVIDER_GPIO_EXPANDER_INIT")\
    X(OWNER_PROVIDER_GPIO_EXPANDER_SET_PINS, 0xD002, "OWNER_PROVIDER_GPIO_EXPANDER_SET_PINS")\
    X(OWNER_PROVIDER_GPIO_EXPANDER_READ_PINS, 0xD003, "OWNER_PROVIDER_GPIO_EXPANDER_READ_PINS")\
    X(OWNER_PROVIDER_GPIO_EXPANDER_TOGGLE_PINS, 0xD004, "OWNER_PROVIDER_GPIO_EXPANDER_TOGGLE_PINS")\
    X(OWNER_PROVIDER_GPIO_EXPANDER_SET_CALLBACK, 0xD005, "OWNER_PROVIDER_GPIO_EXPANDER_SET_CALLBACK")\
    X(OWNER_PROVIDER_GPIO_EXPANDER_CONFIGURE_PINS, 0xD006, "OWNER_PROVIDER_GPIO_EXPANDER_CONFIGURE_PINS")

#define PROVIDER_GPIO_EXPANDER_ERROR_MAP(X) \
    X(ERR_PROVIDER_GPIO_EXPANDER_BASE, 0xD000, "ERR_PROVIDER_GPIO_EXPANDER_BASE")\
    X(EXPANDER_INVALID_PIN, 0xD001, "EXPANDER_INVALID_PIN")\
    X(EXPANDER_UNSUPPORTED_MODE, 0xD002, "EXPANDER_UNSUPPORTED_MODE")\
    X(EXPANDER_UPDATE_FAILED, 0xD003, "EXPANDER_UPDATE_FAILED")

