export { BlockDetails } from './blocks/BlockDetails'
export { BlockPalette } from './workspace/BlockPalette'
export { blockDiagnostics } from './blocks/blockView'
export { CanvasEditor } from './workspace/CanvasEditor'
export { useCanvasWorkspace } from './workspace/useCanvasWorkspace'
export type { CanvasWorkspace } from './workspace/useCanvasWorkspace'
