"""
Protocol-agnostic BLE client for runIT boards.

Knows nothing about the wire format (class/packet headers, payload structs) -
just characteristic discovery, per-characteristic notify subscriptions, and
raw byte send/read. `decoder_types.py` (generated by sync_decoders_from_c.py)
and the GUI layer build the actual runIT packets on top of this.
"""
import logging
from typing import Dict, List, Optional, Callable, Union
from bleak import BleakScanner, BleakClient
from bleak.backends.characteristic import BleakGATTCharacteristic

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("RunIT_BLE")

NotifyCallback = Callable[[int, BleakGATTCharacteristic, bytes], None]


def to_short_uuid(uuid_str: str) -> str:
    """Format a standard or Bleak UUID to a clean 16-bit hex form (e.g. '0xFFE1')."""
    clean = str(uuid_str).lower().replace("-", "").replace("0x", "")
    if len(clean) == 32 and clean.startswith("0000") and clean.endswith("00805f9b34fb"):
        return f"0x{clean[4:8].upper()}"
    elif len(clean) == 4:
        return f"0x{clean.upper()}"
    elif len(clean) == 8 and clean.startswith("0000"):
        return f"0x{clean[4:8].upper()}"
    return f"0x{clean[:4].upper()}" if len(clean) >= 4 else f"0x{clean.upper()}"


def format_hex(data: bytes) -> str:
    return " ".join(f"{b:02X}" for b in data)


def format_text(data: bytes) -> str:
    return data.decode("utf-8", errors="replace").replace("\r", "").replace("\n", " ")


class CharInfo:
    """One discovered characteristic plus the metadata the GUI needs."""

    def __init__(self, cid: int, char: BleakGATTCharacteristic, name: str, service_uuid: str):
        self.cid = cid
        self.char = char
        self.name = name
        self.service_uuid = service_uuid
        self.short_uuid = to_short_uuid(char.uuid)
        self.properties = list(char.properties)
        self.is_monitoring = False


class RunITBLEClient:
    """Connects to a runIT board, discovers its GATT layout, and moves raw bytes."""

    def __init__(self, device_name: str = "runit", address: Optional[str] = None):
        self.device_name = device_name
        self.address = address
        self.client: Optional[BleakClient] = None
        self.characteristics: Dict[int, CharInfo] = {}

    async def connect(self, timeout: float = 10.0) -> bool:
        """Find (by name) or dial (by address) the target BLE device."""
        if self.address:
            self.client = BleakClient(self.address)
            await self.client.connect()
            return self.client.is_connected

        device = await BleakScanner.find_device_by_filter(
            lambda d, ad: (d.name and self.device_name.lower() in d.name.lower())
            or (ad.local_name and self.device_name.lower() in ad.local_name.lower()),
            timeout=timeout,
        )
        if not device:
            return False

        self.client = BleakClient(device)
        await self.client.connect()
        return self.client.is_connected

    async def _read_user_descriptor(self, char: BleakGATTCharacteristic) -> Optional[str]:
        """Read the 0x2901 Characteristic User Description descriptor, if present."""
        for desc in char.descriptors:
            if to_short_uuid(desc.uuid) == "0x2901":
                try:
                    raw_val = await self.client.read_gatt_descriptor(desc.handle)
                    text = raw_val.decode("utf-8", errors="replace").strip()
                    if text:
                        return text
                except Exception as e:
                    logger.debug(f"Failed to read 0x2901 descriptor on {char.uuid}: {e}")
        return None

    async def discover_services(self) -> Dict[int, CharInfo]:
        """Enumerate every service/characteristic and read its firmware-supplied name."""
        if not self.client or not self.client.is_connected:
            raise RuntimeError("Client is not connected.")

        self.characteristics.clear()
        cid = 1
        for service in self.client.services:
            for char in service.characteristics:
                name = await self._read_user_descriptor(char) or char.description or "Unknown"
                self.characteristics[cid] = CharInfo(cid, char, name, to_short_uuid(service.uuid))
                cid += 1

        return self.characteristics

    def resolve_char(self, target: Union[CharInfo, int, str]) -> Optional[CharInfo]:
        """Resolve a target characteristic by ID, 16-bit UUID (e.g. 'FFE2'), or name."""
        if isinstance(target, CharInfo):
            return target
        if isinstance(target, int):
            return self.characteristics.get(target)
        if isinstance(target, str):
            clean = target.strip().lower()
            if clean.isdigit():
                return self.characteristics.get(int(clean))
            for info in self.characteristics.values():
                if clean in info.short_uuid.lower() or clean.replace("0x", "") in info.short_uuid.lower() or clean in info.name.lower():
                    return info
        return None

    async def start_notify(self, target: Union[CharInfo, int, str], on_data: NotifyCallback) -> bool:
        """Enable notifications/indications on one characteristic."""
        info = self.resolve_char(target)
        if not info:
            return False
        if "notify" not in info.properties and "indicate" not in info.properties:
            return False

        def _handler(_sender: BleakGATTCharacteristic, data: bytearray):
            on_data(info.cid, info.char, bytes(data))

        await self.client.start_notify(info.char.uuid, _handler)
        info.is_monitoring = True
        return True

    async def stop_notify(self, target: Union[CharInfo, int, str]) -> bool:
        info = self.resolve_char(target)
        if not info:
            return False
        await self.client.stop_notify(info.char.uuid)
        info.is_monitoring = False
        return True

    async def send_bytes(self, target: Union[CharInfo, int, str], data: bytes, response: Optional[bool] = None) -> bool:
        """Write raw bytes to a characteristic."""
        info = self.resolve_char(target)
        if not info:
            raise ValueError(f"Could not resolve characteristic '{target}'")
        if response is None:
            response = "write" in info.properties
        await self.client.write_gatt_char(info.char, data, response=response)
        return True

    async def read_char(self, target: Union[CharInfo, int, str]) -> bytes:
        """Read a readable characteristic's current value."""
        info = self.resolve_char(target)
        if not info:
            raise ValueError(f"Could not resolve characteristic '{target}'")
        return bytes(await self.client.read_gatt_char(info.char))

    async def disconnect(self):
        if self.client and self.client.is_connected:
            await self.client.disconnect()
