"""
AUTO-GENERATED by sync_decoders_from_c.py - do not edit by hand.
Source: components/codecs/decoders/dec_*.h
"""
import ctypes as ct
from enum import IntEnum


class DecoderClass(IntEnum):
    SYS_CONTRACTS = 0x01


# ============================================================================
# dec_sys_contracts.h (class 0x01 - SYS_CONTRACTS)
# ============================================================================

class packet_sys_device_uninstall_t(ct.LittleEndianStructure):
    _pack_ = 1
    _fields_ = [
        ("device_id", ct.c_uint8),
    ]
    _class_header_ = DecoderClass.SYS_CONTRACTS
    _packet_header_ = 0x10
    _action_name_ = "sys_device_uninstall"

class packet_sys_device_reset_t(ct.LittleEndianStructure):
    _pack_ = 1
    _fields_ = [
        ("device_id", ct.c_uint8),
    ]
    _class_header_ = DecoderClass.SYS_CONTRACTS
    _packet_header_ = 0x11
    _action_name_ = "sys_device_reset"

class packet_sys_device_suspend_t(ct.LittleEndianStructure):
    _pack_ = 1
    _fields_ = [
        ("device_id", ct.c_uint8),
    ]
    _class_header_ = DecoderClass.SYS_CONTRACTS
    _packet_header_ = 0x12
    _action_name_ = "sys_device_suspend"

class packet_sys_device_resume_t(ct.LittleEndianStructure):
    _pack_ = 1
    _fields_ = [
        ("device_id", ct.c_uint8),
    ]
    _class_header_ = DecoderClass.SYS_CONTRACTS
    _packet_header_ = 0x13
    _action_name_ = "sys_device_resume"

class packet_sys_device_suspend_all_t(ct.LittleEndianStructure):
    _pack_ = 1
    _fields_ = [
        ("dummy", ct.c_uint8),
    ]
    _class_header_ = DecoderClass.SYS_CONTRACTS
    _packet_header_ = 0x14
    _action_name_ = "sys_device_suspend_all"

class packet_sys_device_resume_all_t(ct.LittleEndianStructure):
    _pack_ = 1
    _fields_ = [
        ("dummy", ct.c_uint8),
    ]
    _class_header_ = DecoderClass.SYS_CONTRACTS
    _packet_header_ = 0x15
    _action_name_ = "sys_device_resume_all"

class packet_sys_device_freeze_t(ct.LittleEndianStructure):
    _pack_ = 1
    _fields_ = [
        ("device_id", ct.c_uint8),
    ]
    _class_header_ = DecoderClass.SYS_CONTRACTS
    _packet_header_ = 0x16
    _action_name_ = "sys_device_freeze"

class packet_sys_device_sync_t(ct.LittleEndianStructure):
    _pack_ = 1
    _fields_ = [
        ("device_id", ct.c_uint8),
    ]
    _class_header_ = DecoderClass.SYS_CONTRACTS
    _packet_header_ = 0x17
    _action_name_ = "sys_device_sync"

class packet_sys_device_freeze_all_t(ct.LittleEndianStructure):
    _pack_ = 1
    _fields_ = [
        ("dummy", ct.c_uint8),
    ]
    _class_header_ = DecoderClass.SYS_CONTRACTS
    _packet_header_ = 0x18
    _action_name_ = "sys_device_freeze_all"

class packet_sys_device_sync_all_t(ct.LittleEndianStructure):
    _pack_ = 1
    _fields_ = [
        ("dummy", ct.c_uint8),
    ]
    _class_header_ = DecoderClass.SYS_CONTRACTS
    _packet_header_ = 0x19
    _action_name_ = "sys_device_sync_all"

class packet_sys_io_reset_t(ct.LittleEndianStructure):
    _pack_ = 1
    _fields_ = [
        ("device_id", ct.c_uint8),
        ("pin", ct.c_uint8),
    ]
    _class_header_ = DecoderClass.SYS_CONTRACTS
    _packet_header_ = 0x20
    _action_name_ = "sys_io_reset"

class packet_sys_io_set_mode_t(ct.LittleEndianStructure):
    _pack_ = 1
    _fields_ = [
        ("device_id", ct.c_uint8),
        ("pin", ct.c_uint8),
        ("mode", ct.c_uint8),
    ]
    _class_header_ = DecoderClass.SYS_CONTRACTS
    _packet_header_ = 0x21
    _action_name_ = "sys_io_set_mode"

class packet_sys_io_set_level_t(ct.LittleEndianStructure):
    _pack_ = 1
    _fields_ = [
        ("device_id", ct.c_uint8),
        ("pin", ct.c_uint8),
        ("level", ct.c_uint8),
    ]
    _class_header_ = DecoderClass.SYS_CONTRACTS
    _packet_header_ = 0x22
    _action_name_ = "sys_io_set_level"

class packet_sys_io_get_level_t(ct.LittleEndianStructure):
    _pack_ = 1
    _fields_ = [
        ("device_id", ct.c_uint8),
        ("pin", ct.c_uint8),
    ]
    _class_header_ = DecoderClass.SYS_CONTRACTS
    _packet_header_ = 0x23
    _action_name_ = "sys_io_get_level"

class packet_sys_io_toggle_t(ct.LittleEndianStructure):
    _pack_ = 1
    _fields_ = [
        ("device_id", ct.c_uint8),
        ("pin", ct.c_uint8),
    ]
    _class_header_ = DecoderClass.SYS_CONTRACTS
    _packet_header_ = 0x24
    _action_name_ = "sys_io_toggle"

class packet_sys_io_get_voltage_t(ct.LittleEndianStructure):
    _pack_ = 1
    _fields_ = [
        ("device_id", ct.c_uint8),
        ("pin", ct.c_uint8),
    ]
    _class_header_ = DecoderClass.SYS_CONTRACTS
    _packet_header_ = 0x25
    _action_name_ = "sys_io_get_voltage"

class packet_sys_io_set_voltage_t(ct.LittleEndianStructure):
    _pack_ = 1
    _fields_ = [
        ("device_id", ct.c_uint8),
        ("pin", ct.c_uint8),
        ("voltage_mV", ct.c_uint32),
    ]
    _class_header_ = DecoderClass.SYS_CONTRACTS
    _packet_header_ = 0x26
    _action_name_ = "sys_io_set_voltage"

class packet_sys_io_set_pwm_frequency_t(ct.LittleEndianStructure):
    _pack_ = 1
    _fields_ = [
        ("device_id", ct.c_uint8),
        ("pin", ct.c_uint8),
        ("frequency_HZ", ct.c_uint32),
    ]
    _class_header_ = DecoderClass.SYS_CONTRACTS
    _packet_header_ = 0x27
    _action_name_ = "sys_io_set_pwm_frequency"

class packet_sys_io_set_pwm_duty_t(ct.LittleEndianStructure):
    _pack_ = 1
    _fields_ = [
        ("device_id", ct.c_uint8),
        ("pin", ct.c_uint8),
        ("duty", ct.c_uint32),
    ]
    _class_header_ = DecoderClass.SYS_CONTRACTS
    _packet_header_ = 0x28
    _action_name_ = "sys_io_set_pwm_duty"

class packet_sys_power_budget_update_source_t(ct.LittleEndianStructure):
    _pack_ = 1
    _fields_ = [
        ("max_mV", ct.c_uint32),
        ("max_mA", ct.c_uint32),
    ]
    _class_header_ = DecoderClass.SYS_CONTRACTS
    _packet_header_ = 0x30
    _action_name_ = "sys_power_budget_update_source"

class packet_sys_vreg_set_enable_t(ct.LittleEndianStructure):
    _pack_ = 1
    _fields_ = [
        ("device_id", ct.c_uint8),
        ("state", ct.c_uint8),
    ]
    _class_header_ = DecoderClass.SYS_CONTRACTS
    _packet_header_ = 0x31
    _action_name_ = "sys_vreg_set_enable"

class packet_sys_vreg_set_voltage_t(ct.LittleEndianStructure):
    _pack_ = 1
    _fields_ = [
        ("device_id", ct.c_uint8),
        ("voltage_mV", ct.c_uint32),
    ]
    _class_header_ = DecoderClass.SYS_CONTRACTS
    _packet_header_ = 0x32
    _action_name_ = "sys_vreg_set_voltage"

class packet_sys_vreg_set_current_t(ct.LittleEndianStructure):
    _pack_ = 1
    _fields_ = [
        ("device_id", ct.c_uint8),
        ("current_mA", ct.c_uint32),
    ]
    _class_header_ = DecoderClass.SYS_CONTRACTS
    _packet_header_ = 0x33
    _action_name_ = "sys_vreg_set_current"

class packet_sys_power_monitor_get_voltage_t(ct.LittleEndianStructure):
    _pack_ = 1
    _fields_ = [
        ("device_id", ct.c_uint8),
        ("channel", ct.c_uint8),
    ]
    _class_header_ = DecoderClass.SYS_CONTRACTS
    _packet_header_ = 0x34
    _action_name_ = "sys_power_monitor_get_voltage"

class packet_sys_power_monitor_get_current_t(ct.LittleEndianStructure):
    _pack_ = 1
    _fields_ = [
        ("device_id", ct.c_uint8),
        ("channel", ct.c_uint8),
    ]
    _class_header_ = DecoderClass.SYS_CONTRACTS
    _packet_header_ = 0x35
    _action_name_ = "sys_power_monitor_get_current"

class packet_sys_power_usb_pd_set_t(ct.LittleEndianStructure):
    _pack_ = 1
    _fields_ = [
        ("device_id", ct.c_uint8),
        ("voltage_mV", ct.c_uint32),
        ("current_mA", ct.c_uint32),
    ]
    _class_header_ = DecoderClass.SYS_CONTRACTS
    _packet_header_ = 0x36
    _action_name_ = "sys_power_usb_pd_set"

class packet_sys_power_usb_pd_list_t(ct.LittleEndianStructure):
    _pack_ = 1
    _fields_ = [
        ("device_id", ct.c_uint8),
    ]
    _class_header_ = DecoderClass.SYS_CONTRACTS
    _packet_header_ = 0x37
    _action_name_ = "sys_power_usb_pd_list"

class packet_sys_power_usb_pd_get_limits_t(ct.LittleEndianStructure):
    _pack_ = 1
    _fields_ = [
        ("device_id", ct.c_uint8),
    ]
    _class_header_ = DecoderClass.SYS_CONTRACTS
    _packet_header_ = 0x38
    _action_name_ = "sys_power_usb_pd_get_limits"

# ============================================================================
# Registry - every generated packet struct, source order. Drives the GUI's
# class -> packet -> form auto command builder.
# ============================================================================
PACKET_REGISTRY = [
    packet_sys_device_uninstall_t,
    packet_sys_device_reset_t,
    packet_sys_device_suspend_t,
    packet_sys_device_resume_t,
    packet_sys_device_suspend_all_t,
    packet_sys_device_resume_all_t,
    packet_sys_device_freeze_t,
    packet_sys_device_sync_t,
    packet_sys_device_freeze_all_t,
    packet_sys_device_sync_all_t,
    packet_sys_io_reset_t,
    packet_sys_io_set_mode_t,
    packet_sys_io_set_level_t,
    packet_sys_io_get_level_t,
    packet_sys_io_toggle_t,
    packet_sys_io_get_voltage_t,
    packet_sys_io_set_voltage_t,
    packet_sys_io_set_pwm_frequency_t,
    packet_sys_io_set_pwm_duty_t,
    packet_sys_power_budget_update_source_t,
    packet_sys_vreg_set_enable_t,
    packet_sys_vreg_set_voltage_t,
    packet_sys_vreg_set_current_t,
    packet_sys_power_monitor_get_voltage_t,
    packet_sys_power_monitor_get_current_t,
    packet_sys_power_usb_pd_set_t,
    packet_sys_power_usb_pd_list_t,
    packet_sys_power_usb_pd_get_limits_t,
]
