#pragma once

// Owner-only map for provider components
#define PROVIDER_OWNER_MAP(X) \
    X(OWNER_PROVIDER_CURRENT_MONITOR, 0xe901, "OWNER_PROVIDER_CURRENT_MONITOR") \
    X(OWNER_PROVIDER_VREG, 0xe902, "OWNER_PROVIDER_VREG") \
    X(OWNER_PROVIDER_GPIO_EXPANDER, 0xe903, "OWNER_PROVIDER_GPIO_EXPANDER") \
    X(OWNER_PROVIDER_ADC_EXPANDER, 0xe904, "OWNER_PROVIDER_ADC_EXPANDER") \
    X(OWNER_PROVIDER_PWM_EXPANDER, 0xe905, "OWNER_PROVIDER_PWM_EXPANDER") \
    X(OWNER_PROVIDER_GPIO_ESP, 0xe906, "OWNER_PROVIDER_GPIO_ESP")

