#pragma once

// Owner-only map for provider components
#define PROVIDER_OWNER_MAP(X) \
    X(OWNER_PROVIDER_CURRENT_MONITOR, 0xe901, "OWNER_PROVIDER_CURRENT_MONITOR") \
    X(OWNER_PROVIDER_VREG, 0xe902, "OWNER_PROVIDER_VREG") \
    X(OWNER_PROVIDER_GPIO_EXPANDER, 0xe223, "OWNER_PROVIDER_GPIO_EXPANDER") \
    X(OWNER_PROVIDER_ADC_EXPANDER, 0xe224, "OWNER_PROVIDER_ADC_EXPANDER") \
    X(OWNER_PROVIDER_PWM_EXPANDER, 0xe225, "OWNER_PROVIDER_PWM_EXPANDER") \
    X(OWNER_PROVIDER_GPIO_ESP, 0xe216, "OWNER_PROVIDER_GPIO_ESP") \
    X(OWNER_PROVIDER_POWER_DELIVERY, 0xe217, "OWNER_PROVIDER_POWER_DELIVERY") \
    X(OWNER_PROVIDER_DAC_EXPANDER, 0xe218, "OWNER_PROVIDER_DAC_EXPANDER") \

