#pragma once
#include <stdint.h>
#include "esp_err.h"

#define SYS_BLE_OWNER_MAP(X) \
  X(OWNER_SYS_BLE_BASE, 0xA500, "OWNER_SYS_BLE_BASE") \
  X(OWNER_SYS_BLE_CREATE, 0xA501, "OWNER_SYS_BLE_CREATE") \
  X(OWNER_SYS_BLE_SERVICE_CREATE, 0xA502, "OWNER_SYS_BLE_SERVICE_CREATE") \
  X(OWNER_SYS_BLE_SERVICE_REMOVE, 0xA503, "OWNER_SYS_BLE_SERVICE_REMOVE") \
  X(OWNER_SYS_BLE_CHAR_CREATE, 0xA504, "OWNER_SYS_BLE_CHAR_CREATE") \
  X(OWNER_SYS_BLE_CHAR_REMOVE, 0xA505, "OWNER_SYS_BLE_CHAR_REMOVE") \
  X(OWNER_SYS_BLE_CHAR_ASSIGN_TX, 0xA506, "OWNER_SYS_BLE_CHAR_ASSIGN_TX") \
  X(OWNER_SYS_BLE_SEND, 0xA507, "OWNER_SYS_BLE_SEND") \
  X(OWNER_SYS_BLE_DATABASE_SYNC, 0xA508, "OWNER_SYS_BLE_DATABASE_SYNC") \
  X(OWNER_SYS_BLE_GET_STATUS, 0xA509, "OWNER_SYS_BLE_GET_STATUS") \
  X(OWNER_SYS_BLE_ADV, 0xA50A, "OWNER_SYS_BLE_ADV") \
  X(OWNER_SYS_BLE_STACK, 0xA50B, "OWNER_SYS_BLE_STACK")

#define SYS_ERROR_BLE_MAP(X) \
  X(ERR_BLE_STACK_FAILED, struct { esp_err_t rc; }) \
  X(ERR_BLE_HARDWARE_FAULT, struct { esp_err_t rc; }) \
  X(ERR_BLE_ADV_FAILED, struct { esp_err_t rc; }) \
  X(ERR_BLE_GATT_FAILED, struct { esp_err_t rc; })
