#pragma once

#define STATUS_PAYLOAD_BLE_CHAR 10
#define STATUS_PAYLOAD_BLE_SVC  11

#define SYS_BLE_OWNER_MAP(X)                                           \
  X(OWNER_SYS_BLE_BASE, 0xA500, "OWNER_SYS_BLE_BASE")                  \
  X(OWNER_SYS_BLE_CREATE, 0xA501, "OWNER_SYS_BLE_CREATE")              \
  X(OWNER_SYS_BLE_SERVICE_CREATE, 0xA502, "OWNER_SYS_BLE_SERVICE_CREATE") \
  X(OWNER_SYS_BLE_SERVICE_REMOVE, 0xA503, "OWNER_SYS_BLE_SERVICE_REMOVE") \
  X(OWNER_SYS_BLE_CHAR_CREATE, 0xA504, "OWNER_SYS_BLE_CHAR_CREATE")    \
  X(OWNER_SYS_BLE_CHAR_REMOVE, 0xA505, "OWNER_SYS_BLE_CHAR_REMOVE")    \
  X(OWNER_SYS_BLE_CHAR_ASSIGN_TX, 0xA506, "OWNER_SYS_BLE_CHAR_ASSIGN_TX") \
  X(OWNER_SYS_BLE_SEND, 0xA507, "OWNER_SYS_BLE_SEND")                  \
  X(OWNER_SYS_BLE_DATABASE_SYNC, 0xA508, "OWNER_SYS_BLE_DATABASE_SYNC")\
  X(OWNER_SYS_BLE_GET_STATUS, 0xA509, "OWNER_SYS_BLE_GET_STATUS")      \
  X(OWNER_SYS_BLE_ADV, 0xA50A, "OWNER_SYS_BLE_ADV")                    \
  X(OWNER_SYS_BLE_STACK, 0xA50B, "OWNER_SYS_BLE_STACK")

#define SYS_BLE_ERROR_MAP(X)                                           \
  X(ERR_SYS_BLE_BASE, 0xA500, "ERR_SYS_BLE_BASE")                      \
  X(ERR_BLE_ADV_FAILED, 0xA501, "ERR_BLE_ADV_FAILED")                  \
  X(ERR_BLE_GATT_FAILED, 0xA502, "ERR_BLE_GATT_FAILED")                \
  X(ERR_BLE_STACK_FAILED, 0xA503, "ERR_BLE_STACK_FAILED")
