#pragma once
#include <stdint.h>

#define SYS_POWER_OWNER_MAP(X) \
  X(OWNER_SYS_POWER_BASE, 0xA400, "OWNER_SYS_POWER_BASE") \
  X(OWNER_SYS_POWER_BUDGET_UPDATE_SOURCE, 0xA401, "OWNER_SYS_POWER_BUDGET_UPDATE_SOURCE") \
  X(OWNER_SYS_POWER_REGISTER_VREG, 0xA402, "OWNER_SYS_POWER_REGISTER_VREG") \
  X(OWNER_SYS_POWER_REGISTER_MONITOR, 0xA403, "OWNER_SYS_POWER_REGISTER_MONITOR") \
  X(OWNER_SYS_POWER_REGISTER_USB_PD, 0xA404, "OWNER_SYS_POWER_REGISTER_USB_PD") \
  X(OWNER_SYS_POWER_UNREGISTER, 0xA405, "OWNER_SYS_POWER_UNREGISTER") \
  X(OWNER_SYS_VREG_SET_ENABLE, 0xA406, "OWNER_SYS_VREG_SET_ENABLE") \
  X(OWNER_SYS_VREG_SET_VOLTAGE, 0xA407, "OWNER_SYS_VREG_SET_VOLTAGE") \
  X(OWNER_SYS_VREG_SET_CURRENT, 0xA408, "OWNER_SYS_VREG_SET_CURRENT") \
  X(OWNER_SYS_VREG_ADD_CALLBACK, 0xA409, "OWNER_SYS_VREG_ADD_CALLBACK") \
  X(OWNER_SYS_POWER_MONITOR_GET_VOLTAGE, 0xA40A, "OWNER_SYS_POWER_MONITOR_GET_VOLTAGE") \
  X(OWNER_SYS_POWER_MONITOR_GET_CURRENT, 0xA40B, "OWNER_SYS_POWER_MONITOR_GET_CURRENT") \
  X(OWNER_SYS_POWER_MONITOR_ADD_CALLBACK, 0xA40C, "OWNER_SYS_POWER_MONITOR_ADD_CALLBACK") \
  X(OWNER_SYS_POWER_USB_PD_SET, 0xA40D, "OWNER_SYS_POWER_USB_PD_SET") \
  X(OWNER_SYS_POWER_USB_PD_LIST, 0xA40E, "OWNER_SYS_POWER_USB_PD_LIST") \
  X(OWNER_SYS_POWER_USB_PD_GET_LIMITS, 0xA40F, "OWNER_SYS_POWER_USB_PD_GET_LIMITS")

#define SYS_ERROR_POWER_MAP(X) \
  X(ERR_POWER_BUDGET_EXCEEDED, struct { uint8_t device_id; })
