#pragma once

#define VM_OWNER_MAP(X) \
    X(OWNER_VM, 0x9000, "OWNER_VM") \
    X(VM_OWNER_CALLBACK_ADD, 0x9011, "VM_OWNER_CALLBACK_ADD") \
    X(VM_OWNER_CALLBACK_REMOVE, 0x9012, "VM_OWNER_CALLBACK_REMOVE")

#define VM_ERROR_MAP(X) \
    X(VM_ERR_BASE, 0x9000, "VM_ERR_BASE") \
    X(VM_ERR_CB_TYPE_INVALID, 0x9010, "INVALID CALLBACK TYPE") 
