const assert = require('node:assert/strict');
const decoder = require('../../Python/PythonRunIT/web_ui/stream_decoder.js');
const v2 = Uint8Array.from([2, 1, 255, 0x78, 0x56, 0x34, 0x12, 1, 0, 0, 0, 0xa3, 42]);
const result = decoder.decodeBinaryErrorPacket(v2);
assert.equal(result.schemaId, 0x12345678);
assert.equal(result.schemaKnown, false);
assert.equal(result.isTruncated, true);
assert.equal(result.nodes.length, 1);
assert.deepEqual(result.nodes[0].payload.rawBytes, [42]);
assert.equal(result.nodes[0].tagName, 'ERR_TAG_0x0');
assert.throws(() => decoder.decodeBinaryErrorPacket(v2.slice(0, 4)));
assert.throws(() => decoder.decodeBinaryErrorPacket(Uint8Array.from([9, 0, 0])));
assert.equal(decoder.decodeBinaryErrorPacket(Uint8Array.from([1, 0, 0])).nodes.length, 0);
console.log('PASS: error decoder version/schema/truncation checks');
