#pragma once

#define MANAGER_PWR_OWNER_MAP(X) \
    X(OWNER_MANAGER_PWR, 0xd000, "OWNER_MANAGER_PWR") \
    X(OWNER_MANAGER_PWR_READ_VREG, 0xd001, "OWNER_MANAGER_PWR_READ_VREG") \
    X(OWNER_MANAGER_PWR_READ_CURRENT_MONITOR_VOLTAGE, 0xd002, "OWNER_MANAGER_PWR_READ_CURRENT_MONITOR_VOLTAGE") \
    X(OWNER_MANAGER_PWR_READ_CURRENT_MONITOR_CURRENT, 0xd003, "OWNER_MANAGER_PWR_READ_CURRENT_MONITOR_CURRENT") \
    X(OWNER_MANAGER_PWR_SET_PARAM_VREG, 0xd004, "OWNER_MANAGER_PWR_SET_PARAM_VREG") \
    X(OWNER_MANAGER_PWR_EN_VREG, 0xd005, "OWNER_MANAGER_PWR_EN_VREG") \
    X(OWNER_MANAGER_PWR_CONFIG_CURRENT_MONITOR, 0xd006, "OWNER_MANAGER_PWR_CONFIG_CURRENT_MONITOR") \
    X(OWNER_MANAGER_PWR_REGISTER_CALLBACK, 0xd008, "OWNER_MANAGER_PWR_REGISTER_CALLBACK") \
    X(OWNER_MANAGER_PWR_PARSE_PACKET, 0xd010, "OWNER_MANAGER_PWR_PARSE_PACKET") \
    X(OWNER_MANAGER_PWR_CONFIG_PD, 0xd011, "OWNER_MANAGER_PWR_CONFIG_PD") \
    X(OWNER_MANAGER_PWR_READ_PD_VOLTAGE,0xd012, "OWNER_MANAGER_PWR_READ_PD_VOLTAGE") \
    X(OWNER_MANAGER_PWR_READ_PD_CURRENT,0xd013, "OWNER_MANAGER_PWR_READ_PD_CURRENT" ) \
    X(OWNER_MANAGER_PWR_SET_DAC, 0xd014, "OWNER_MANAGER_PWR_SET_DAC") \
    X(OWNER_MANAGER_PWR_GET_DAC, 0xd015, "OWNER_MANAGER_PWR_GET_DAC") \

#define PWR_ERROR_MAP(X) \
    X(PWR_ERR_BASE, 0xd000, "PWR_ERR_BASE")\
    X(PWR_ERR_DEVICE_NOT_FOUND, 0xd001, "PWR device not found")\
    X(PWR_ERR_INVALID_PARAM, 0xd002, "Invalid PWR configuration parameter")\
    X(PWR_ERR_FEATURE_UNSUPPORTED, 0xd003, "PWR feature is unsupported at the moment")\
    X(PWR_ERR_UPDATE_FAILED, 0xd007, "PWR update failed")\
    X(PWE_ERR_PARSE_NOT_FOUND, 0xd008, "PWR config packet parse failed - no matching config found")\
    X(PWE_ERR_PARSE_FAILED, 0xd009, "Applying packet failed")


