#pragma once

#define PROVIDER_VREG_OWNER_MAP(X) \
    X(OWNER_PROVIDER_VREG_INIT, 0xB101, "OWNER_PROVIDER_VREG_INIT")\
    X(OWNER_PROVIDER_VREG_SET_PINS, 0xB102, "OWNER_PROVIDER_VREG_SET_PINS")\
    X(OWNER_PROVIDER_VREG_SET_VOLTAGE, 0xB103, "OWNER_PROVIDER_VREG_SET_VOLTAGE")\
    X(OWNER_PROVIDER_VREG_SET_CURRENT_LIMIT, 0xB104, "OWNER_PROVIDER_VREG_SET_CURRENT_LIMIT")\
    X(OWNER_PROVIDER_VREG_EN, 0xB105, "OWNER_PROVIDER_VREG_EN")\
    X(OWNER_PROVIDER_VREG_REGISTER_OCP_CALLBACK, 0xB106, "OWNER_PROVIDER_VREG_REGISTER_OCP_CALLBACK")\
    X(OWNER_PROVIDER_VREG_REGISTER_OVP_CALLBACK, 0xB107, "OWNER_PROVIDER_VREG_REGISTER_OVP_CALLBACK")\
    X(OWNER_PROVIDER_VREG_REGISTER_SCP_CALLBACK, 0xB108, "OWNER_PROVIDER_VREG_REGISTER_SCP_CALLBACK")\

#define PROVIDER_VREG_ERROR_MAP(X) \
    X(ERR_PROVIDER_VREG_BASE, 0xB100, "ERR_PROVIDER_VREG_BASE")
