#pragma once

#define PROVIDER_CURRENT_MONITOR_OWNER_MAP(X) \
    X(OWNER_PROVIDER_CURRENT_MONITOR_INIT, 0xB201, "OWNER_PROVIDER_CURRENT_MONITOR_INIT")\
    X(OWNER_PROVIDER_CURRENT_MONITOR_SET_LIMITS, 0xB202, "OWNER_PROVIDER_CURRENT_MONITOR_SET_LIMITS")\
    X(OWNER_PROVIDER_CURRENT_MONITOR_READ, 0xB203, "OWNER_PROVIDER_CURRENT_MONITOR_READ")

#define PROVIDER_CURRENT_MONITOR_ERROR_MAP(X) \
    X(ERR_PROVIDER_CURRENT_MONITOR_BASE, 0xB200, "ERR_PROVIDER_CURRENT_MONITOR_BASE")
